// Code generated by protoc-gen-go. DO NOT EDIT.
// source: git.liero.se/opentelco/go-swpx/proto/src/traffic_policy.proto

package traffic_policy

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//display current-configuration interface GigabitEthernet0/0/5 | include traffic-policy|shaping
//traffic-policy KBPS_0000 inbound
//traffic-policy KBPS_100000 outbound
//qos queue 0 shaping cir 110000 pir 110000 cbs 2500000 pbs 2500000
type ConfiguredTrafficPolicy struct {
	Inbound  string                       `protobuf:"bytes,1,opt,name=inbound,proto3" json:"inbound,omitempty"`
	Outbound string                       `protobuf:"bytes,2,opt,name=outbound,proto3" json:"outbound,omitempty"`
	Qos      *ConfiguredTrafficPolicy_QOS `protobuf:"bytes,3,opt,name=qos,proto3" json:"qos,omitempty"`
	// display traffic policy statistics interface GigabitEthernet0/0/5 inbound verbose classifier-base
	InboundStatistics    *ConfiguredTrafficPolicy_Statistics `protobuf:"bytes,4,opt,name=inbound_statistics,json=inboundStatistics,proto3" json:"inbound_statistics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *ConfiguredTrafficPolicy) Reset()         { *m = ConfiguredTrafficPolicy{} }
func (m *ConfiguredTrafficPolicy) String() string { return proto.CompactTextString(m) }
func (*ConfiguredTrafficPolicy) ProtoMessage()    {}
func (*ConfiguredTrafficPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_45525d1b2c264c94, []int{0}
}

func (m *ConfiguredTrafficPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfiguredTrafficPolicy.Unmarshal(m, b)
}
func (m *ConfiguredTrafficPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfiguredTrafficPolicy.Marshal(b, m, deterministic)
}
func (m *ConfiguredTrafficPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfiguredTrafficPolicy.Merge(m, src)
}
func (m *ConfiguredTrafficPolicy) XXX_Size() int {
	return xxx_messageInfo_ConfiguredTrafficPolicy.Size(m)
}
func (m *ConfiguredTrafficPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfiguredTrafficPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_ConfiguredTrafficPolicy proto.InternalMessageInfo

func (m *ConfiguredTrafficPolicy) GetInbound() string {
	if m != nil {
		return m.Inbound
	}
	return ""
}

func (m *ConfiguredTrafficPolicy) GetOutbound() string {
	if m != nil {
		return m.Outbound
	}
	return ""
}

func (m *ConfiguredTrafficPolicy) GetQos() *ConfiguredTrafficPolicy_QOS {
	if m != nil {
		return m.Qos
	}
	return nil
}

func (m *ConfiguredTrafficPolicy) GetInboundStatistics() *ConfiguredTrafficPolicy_Statistics {
	if m != nil {
		return m.InboundStatistics
	}
	return nil
}

type ConfiguredTrafficPolicy_QOS struct {
	Queue                int64                                `protobuf:"varint,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Shaping              *ConfiguredTrafficPolicy_QOS_Shaping `protobuf:"bytes,2,opt,name=shaping,proto3" json:"shaping,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *ConfiguredTrafficPolicy_QOS) Reset()         { *m = ConfiguredTrafficPolicy_QOS{} }
func (m *ConfiguredTrafficPolicy_QOS) String() string { return proto.CompactTextString(m) }
func (*ConfiguredTrafficPolicy_QOS) ProtoMessage()    {}
func (*ConfiguredTrafficPolicy_QOS) Descriptor() ([]byte, []int) {
	return fileDescriptor_45525d1b2c264c94, []int{0, 0}
}

func (m *ConfiguredTrafficPolicy_QOS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfiguredTrafficPolicy_QOS.Unmarshal(m, b)
}
func (m *ConfiguredTrafficPolicy_QOS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfiguredTrafficPolicy_QOS.Marshal(b, m, deterministic)
}
func (m *ConfiguredTrafficPolicy_QOS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfiguredTrafficPolicy_QOS.Merge(m, src)
}
func (m *ConfiguredTrafficPolicy_QOS) XXX_Size() int {
	return xxx_messageInfo_ConfiguredTrafficPolicy_QOS.Size(m)
}
func (m *ConfiguredTrafficPolicy_QOS) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfiguredTrafficPolicy_QOS.DiscardUnknown(m)
}

var xxx_messageInfo_ConfiguredTrafficPolicy_QOS proto.InternalMessageInfo

func (m *ConfiguredTrafficPolicy_QOS) GetQueue() int64 {
	if m != nil {
		return m.Queue
	}
	return 0
}

func (m *ConfiguredTrafficPolicy_QOS) GetShaping() *ConfiguredTrafficPolicy_QOS_Shaping {
	if m != nil {
		return m.Shaping
	}
	return nil
}

type ConfiguredTrafficPolicy_QOS_Shaping struct {
	Cir                  float64  `protobuf:"fixed64,1,opt,name=cir,proto3" json:"cir,omitempty"`
	Pir                  float64  `protobuf:"fixed64,2,opt,name=pir,proto3" json:"pir,omitempty"`
	Cbs                  float64  `protobuf:"fixed64,3,opt,name=cbs,proto3" json:"cbs,omitempty"`
	Pbs                  float64  `protobuf:"fixed64,4,opt,name=pbs,proto3" json:"pbs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfiguredTrafficPolicy_QOS_Shaping) Reset()         { *m = ConfiguredTrafficPolicy_QOS_Shaping{} }
func (m *ConfiguredTrafficPolicy_QOS_Shaping) String() string { return proto.CompactTextString(m) }
func (*ConfiguredTrafficPolicy_QOS_Shaping) ProtoMessage()    {}
func (*ConfiguredTrafficPolicy_QOS_Shaping) Descriptor() ([]byte, []int) {
	return fileDescriptor_45525d1b2c264c94, []int{0, 0, 0}
}

func (m *ConfiguredTrafficPolicy_QOS_Shaping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfiguredTrafficPolicy_QOS_Shaping.Unmarshal(m, b)
}
func (m *ConfiguredTrafficPolicy_QOS_Shaping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfiguredTrafficPolicy_QOS_Shaping.Marshal(b, m, deterministic)
}
func (m *ConfiguredTrafficPolicy_QOS_Shaping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfiguredTrafficPolicy_QOS_Shaping.Merge(m, src)
}
func (m *ConfiguredTrafficPolicy_QOS_Shaping) XXX_Size() int {
	return xxx_messageInfo_ConfiguredTrafficPolicy_QOS_Shaping.Size(m)
}
func (m *ConfiguredTrafficPolicy_QOS_Shaping) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfiguredTrafficPolicy_QOS_Shaping.DiscardUnknown(m)
}

var xxx_messageInfo_ConfiguredTrafficPolicy_QOS_Shaping proto.InternalMessageInfo

func (m *ConfiguredTrafficPolicy_QOS_Shaping) GetCir() float64 {
	if m != nil {
		return m.Cir
	}
	return 0
}

func (m *ConfiguredTrafficPolicy_QOS_Shaping) GetPir() float64 {
	if m != nil {
		return m.Pir
	}
	return 0
}

func (m *ConfiguredTrafficPolicy_QOS_Shaping) GetCbs() float64 {
	if m != nil {
		return m.Cbs
	}
	return 0
}

func (m *ConfiguredTrafficPolicy_QOS_Shaping) GetPbs() float64 {
	if m != nil {
		return m.Pbs
	}
	return 0
}

type ConfiguredTrafficPolicy_Statistics struct {
	TrafficPolicy string `protobuf:"bytes,1,opt,name=traffic_policy,json=trafficPolicy,proto3" json:"traffic_policy,omitempty"`
	RuleNumber    int64  `protobuf:"varint,2,opt,name=rule_number,json=ruleNumber,proto3" json:"rule_number,omitempty"`
	Status        string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Interval      int64  `protobuf:"varint,4,opt,name=interval,proto3" json:"interval,omitempty"`
	// AS A TABLE
	//        PERMIT       drop        0 pass        0 for KBPS_0000
	//        DISCARD      drop        0 pass        0 for DISCARD
	//        VOIP         drop        0 pass        0 for VOIP
	//        OTHER        drop        0 pass        0 for KBPS_0000
	Classifiers          map[string]*ConfiguredTrafficPolicy_Statistics_Classifier `protobuf:"bytes,5,rep,name=classifiers,proto3" json:"classifiers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                                  `json:"-"`
	XXX_unrecognized     []byte                                                    `json:"-"`
	XXX_sizecache        int32                                                     `json:"-"`
}

func (m *ConfiguredTrafficPolicy_Statistics) Reset()         { *m = ConfiguredTrafficPolicy_Statistics{} }
func (m *ConfiguredTrafficPolicy_Statistics) String() string { return proto.CompactTextString(m) }
func (*ConfiguredTrafficPolicy_Statistics) ProtoMessage()    {}
func (*ConfiguredTrafficPolicy_Statistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_45525d1b2c264c94, []int{0, 1}
}

func (m *ConfiguredTrafficPolicy_Statistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfiguredTrafficPolicy_Statistics.Unmarshal(m, b)
}
func (m *ConfiguredTrafficPolicy_Statistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfiguredTrafficPolicy_Statistics.Marshal(b, m, deterministic)
}
func (m *ConfiguredTrafficPolicy_Statistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfiguredTrafficPolicy_Statistics.Merge(m, src)
}
func (m *ConfiguredTrafficPolicy_Statistics) XXX_Size() int {
	return xxx_messageInfo_ConfiguredTrafficPolicy_Statistics.Size(m)
}
func (m *ConfiguredTrafficPolicy_Statistics) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfiguredTrafficPolicy_Statistics.DiscardUnknown(m)
}

var xxx_messageInfo_ConfiguredTrafficPolicy_Statistics proto.InternalMessageInfo

func (m *ConfiguredTrafficPolicy_Statistics) GetTrafficPolicy() string {
	if m != nil {
		return m.TrafficPolicy
	}
	return ""
}

func (m *ConfiguredTrafficPolicy_Statistics) GetRuleNumber() int64 {
	if m != nil {
		return m.RuleNumber
	}
	return 0
}

func (m *ConfiguredTrafficPolicy_Statistics) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ConfiguredTrafficPolicy_Statistics) GetInterval() int64 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *ConfiguredTrafficPolicy_Statistics) GetClassifiers() map[string]*ConfiguredTrafficPolicy_Statistics_Classifier {
	if m != nil {
		return m.Classifiers
	}
	return nil
}

type ConfiguredTrafficPolicy_Statistics_Classifier struct {
	Classifier           string                                                           `protobuf:"bytes,1,opt,name=classifier,proto3" json:"classifier,omitempty"`
	Behavior             string                                                           `protobuf:"bytes,2,opt,name=behavior,proto3" json:"behavior,omitempty"`
	Board                string                                                           `protobuf:"bytes,3,opt,name=board,proto3" json:"board,omitempty"`
	Metrics              map[string]*ConfiguredTrafficPolicy_Statistics_Classifier_Metric `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                                         `json:"-"`
	XXX_unrecognized     []byte                                                           `json:"-"`
	XXX_sizecache        int32                                                            `json:"-"`
}

func (m *ConfiguredTrafficPolicy_Statistics_Classifier) Reset() {
	*m = ConfiguredTrafficPolicy_Statistics_Classifier{}
}
func (m *ConfiguredTrafficPolicy_Statistics_Classifier) String() string {
	return proto.CompactTextString(m)
}
func (*ConfiguredTrafficPolicy_Statistics_Classifier) ProtoMessage() {}
func (*ConfiguredTrafficPolicy_Statistics_Classifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_45525d1b2c264c94, []int{0, 1, 1}
}

func (m *ConfiguredTrafficPolicy_Statistics_Classifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfiguredTrafficPolicy_Statistics_Classifier.Unmarshal(m, b)
}
func (m *ConfiguredTrafficPolicy_Statistics_Classifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfiguredTrafficPolicy_Statistics_Classifier.Marshal(b, m, deterministic)
}
func (m *ConfiguredTrafficPolicy_Statistics_Classifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfiguredTrafficPolicy_Statistics_Classifier.Merge(m, src)
}
func (m *ConfiguredTrafficPolicy_Statistics_Classifier) XXX_Size() int {
	return xxx_messageInfo_ConfiguredTrafficPolicy_Statistics_Classifier.Size(m)
}
func (m *ConfiguredTrafficPolicy_Statistics_Classifier) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfiguredTrafficPolicy_Statistics_Classifier.DiscardUnknown(m)
}

var xxx_messageInfo_ConfiguredTrafficPolicy_Statistics_Classifier proto.InternalMessageInfo

func (m *ConfiguredTrafficPolicy_Statistics_Classifier) GetClassifier() string {
	if m != nil {
		return m.Classifier
	}
	return ""
}

func (m *ConfiguredTrafficPolicy_Statistics_Classifier) GetBehavior() string {
	if m != nil {
		return m.Behavior
	}
	return ""
}

func (m *ConfiguredTrafficPolicy_Statistics_Classifier) GetBoard() string {
	if m != nil {
		return m.Board
	}
	return ""
}

func (m *ConfiguredTrafficPolicy_Statistics_Classifier) GetMetrics() map[string]*ConfiguredTrafficPolicy_Statistics_Classifier_Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type ConfiguredTrafficPolicy_Statistics_Classifier_Metric struct {
	Values               map[string]float64 `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ConfiguredTrafficPolicy_Statistics_Classifier_Metric) Reset() {
	*m = ConfiguredTrafficPolicy_Statistics_Classifier_Metric{}
}
func (m *ConfiguredTrafficPolicy_Statistics_Classifier_Metric) String() string {
	return proto.CompactTextString(m)
}
func (*ConfiguredTrafficPolicy_Statistics_Classifier_Metric) ProtoMessage() {}
func (*ConfiguredTrafficPolicy_Statistics_Classifier_Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_45525d1b2c264c94, []int{0, 1, 1, 1}
}

func (m *ConfiguredTrafficPolicy_Statistics_Classifier_Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfiguredTrafficPolicy_Statistics_Classifier_Metric.Unmarshal(m, b)
}
func (m *ConfiguredTrafficPolicy_Statistics_Classifier_Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfiguredTrafficPolicy_Statistics_Classifier_Metric.Marshal(b, m, deterministic)
}
func (m *ConfiguredTrafficPolicy_Statistics_Classifier_Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfiguredTrafficPolicy_Statistics_Classifier_Metric.Merge(m, src)
}
func (m *ConfiguredTrafficPolicy_Statistics_Classifier_Metric) XXX_Size() int {
	return xxx_messageInfo_ConfiguredTrafficPolicy_Statistics_Classifier_Metric.Size(m)
}
func (m *ConfiguredTrafficPolicy_Statistics_Classifier_Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfiguredTrafficPolicy_Statistics_Classifier_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_ConfiguredTrafficPolicy_Statistics_Classifier_Metric proto.InternalMessageInfo

func (m *ConfiguredTrafficPolicy_Statistics_Classifier_Metric) GetValues() map[string]float64 {
	if m != nil {
		return m.Values
	}
	return nil
}

type QOS struct {
	QueueStatistics      []*QOS_QueueStatistics `protobuf:"bytes,1,rep,name=queue_statistics,json=queueStatistics,proto3" json:"queue_statistics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *QOS) Reset()         { *m = QOS{} }
func (m *QOS) String() string { return proto.CompactTextString(m) }
func (*QOS) ProtoMessage()    {}
func (*QOS) Descriptor() ([]byte, []int) {
	return fileDescriptor_45525d1b2c264c94, []int{1}
}

func (m *QOS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QOS.Unmarshal(m, b)
}
func (m *QOS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QOS.Marshal(b, m, deterministic)
}
func (m *QOS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QOS.Merge(m, src)
}
func (m *QOS) XXX_Size() int {
	return xxx_messageInfo_QOS.Size(m)
}
func (m *QOS) XXX_DiscardUnknown() {
	xxx_messageInfo_QOS.DiscardUnknown(m)
}

var xxx_messageInfo_QOS proto.InternalMessageInfo

func (m *QOS) GetQueueStatistics() []*QOS_QueueStatistics {
	if m != nil {
		return m.QueueStatistics
	}
	return nil
}

type QOS_QueueStatistics struct {
	QueueId              int64    `protobuf:"varint,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	Cir                  float64  `protobuf:"fixed64,2,opt,name=cir,proto3" json:"cir,omitempty"`
	Pir                  float64  `protobuf:"fixed64,3,opt,name=pir,proto3" json:"pir,omitempty"`
	PassedPackets        int64    `protobuf:"varint,4,opt,name=passed_packets,json=passedPackets,proto3" json:"passed_packets,omitempty"`
	PassedRatePps        float64  `protobuf:"fixed64,5,opt,name=passed_rate_pps,json=passedRatePps,proto3" json:"passed_rate_pps,omitempty"`
	PassedBytes          int64    `protobuf:"varint,6,opt,name=passed_bytes,json=passedBytes,proto3" json:"passed_bytes,omitempty"`
	PassedRateBps        float64  `protobuf:"fixed64,7,opt,name=passed_rate_bps,json=passedRateBps,proto3" json:"passed_rate_bps,omitempty"`
	DroppedPackets       int64    `protobuf:"varint,8,opt,name=dropped_packets,json=droppedPackets,proto3" json:"dropped_packets,omitempty"`
	DroppedRatePps       float64  `protobuf:"fixed64,9,opt,name=dropped_rate_pps,json=droppedRatePps,proto3" json:"dropped_rate_pps,omitempty"`
	DroppedBytes         int64    `protobuf:"varint,10,opt,name=dropped_bytes,json=droppedBytes,proto3" json:"dropped_bytes,omitempty"`
	DroppedRateBps       float64  `protobuf:"fixed64,11,opt,name=dropped_rate_bps,json=droppedRateBps,proto3" json:"dropped_rate_bps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QOS_QueueStatistics) Reset()         { *m = QOS_QueueStatistics{} }
func (m *QOS_QueueStatistics) String() string { return proto.CompactTextString(m) }
func (*QOS_QueueStatistics) ProtoMessage()    {}
func (*QOS_QueueStatistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_45525d1b2c264c94, []int{1, 0}
}

func (m *QOS_QueueStatistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QOS_QueueStatistics.Unmarshal(m, b)
}
func (m *QOS_QueueStatistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QOS_QueueStatistics.Marshal(b, m, deterministic)
}
func (m *QOS_QueueStatistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QOS_QueueStatistics.Merge(m, src)
}
func (m *QOS_QueueStatistics) XXX_Size() int {
	return xxx_messageInfo_QOS_QueueStatistics.Size(m)
}
func (m *QOS_QueueStatistics) XXX_DiscardUnknown() {
	xxx_messageInfo_QOS_QueueStatistics.DiscardUnknown(m)
}

var xxx_messageInfo_QOS_QueueStatistics proto.InternalMessageInfo

func (m *QOS_QueueStatistics) GetQueueId() int64 {
	if m != nil {
		return m.QueueId
	}
	return 0
}

func (m *QOS_QueueStatistics) GetCir() float64 {
	if m != nil {
		return m.Cir
	}
	return 0
}

func (m *QOS_QueueStatistics) GetPir() float64 {
	if m != nil {
		return m.Pir
	}
	return 0
}

func (m *QOS_QueueStatistics) GetPassedPackets() int64 {
	if m != nil {
		return m.PassedPackets
	}
	return 0
}

func (m *QOS_QueueStatistics) GetPassedRatePps() float64 {
	if m != nil {
		return m.PassedRatePps
	}
	return 0
}

func (m *QOS_QueueStatistics) GetPassedBytes() int64 {
	if m != nil {
		return m.PassedBytes
	}
	return 0
}

func (m *QOS_QueueStatistics) GetPassedRateBps() float64 {
	if m != nil {
		return m.PassedRateBps
	}
	return 0
}

func (m *QOS_QueueStatistics) GetDroppedPackets() int64 {
	if m != nil {
		return m.DroppedPackets
	}
	return 0
}

func (m *QOS_QueueStatistics) GetDroppedRatePps() float64 {
	if m != nil {
		return m.DroppedRatePps
	}
	return 0
}

func (m *QOS_QueueStatistics) GetDroppedBytes() int64 {
	if m != nil {
		return m.DroppedBytes
	}
	return 0
}

func (m *QOS_QueueStatistics) GetDroppedRateBps() float64 {
	if m != nil {
		return m.DroppedRateBps
	}
	return 0
}

func init() {
	proto.RegisterType((*ConfiguredTrafficPolicy)(nil), "traffic_policy.ConfiguredTrafficPolicy")
	proto.RegisterType((*ConfiguredTrafficPolicy_QOS)(nil), "traffic_policy.ConfiguredTrafficPolicy.QOS")
	proto.RegisterType((*ConfiguredTrafficPolicy_QOS_Shaping)(nil), "traffic_policy.ConfiguredTrafficPolicy.QOS.Shaping")
	proto.RegisterType((*ConfiguredTrafficPolicy_Statistics)(nil), "traffic_policy.ConfiguredTrafficPolicy.Statistics")
	proto.RegisterMapType((map[string]*ConfiguredTrafficPolicy_Statistics_Classifier)(nil), "traffic_policy.ConfiguredTrafficPolicy.Statistics.ClassifiersEntry")
	proto.RegisterType((*ConfiguredTrafficPolicy_Statistics_Classifier)(nil), "traffic_policy.ConfiguredTrafficPolicy.Statistics.Classifier")
	proto.RegisterMapType((map[string]*ConfiguredTrafficPolicy_Statistics_Classifier_Metric)(nil), "traffic_policy.ConfiguredTrafficPolicy.Statistics.Classifier.MetricsEntry")
	proto.RegisterType((*ConfiguredTrafficPolicy_Statistics_Classifier_Metric)(nil), "traffic_policy.ConfiguredTrafficPolicy.Statistics.Classifier.Metric")
	proto.RegisterMapType((map[string]float64)(nil), "traffic_policy.ConfiguredTrafficPolicy.Statistics.Classifier.Metric.ValuesEntry")
	proto.RegisterType((*QOS)(nil), "traffic_policy.QOS")
	proto.RegisterType((*QOS_QueueStatistics)(nil), "traffic_policy.QOS.QueueStatistics")
}

func init() {
	proto.RegisterFile("git.liero.se/opentelco/go-swpx/proto/src/traffic_policy.proto", fileDescriptor_45525d1b2c264c94)
}

var fileDescriptor_45525d1b2c264c94 = []byte{
	// 738 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcd, 0x4e, 0xdb, 0x4a,
	0x14, 0x96, 0xf1, 0x25, 0x81, 0x63, 0x20, 0xb9, 0x23, 0x74, 0xaf, 0xeb, 0x45, 0x4b, 0x41, 0xb4,
	0x91, 0xaa, 0x3a, 0x52, 0x90, 0x2a, 0x5a, 0x89, 0x4d, 0x68, 0x17, 0xad, 0x04, 0x24, 0x4e, 0xd5,
	0x05, 0x9b, 0xc8, 0x3f, 0x93, 0x30, 0x22, 0xd8, 0xc3, 0xcc, 0x98, 0x96, 0x45, 0xa5, 0x3e, 0x40,
	0x1f, 0xa1, 0xaf, 0xd0, 0x47, 0xe8, 0xdb, 0x74, 0xd1, 0x37, 0xe8, 0xb6, 0x9a, 0x1f, 0x27, 0x8e,
	0xa1, 0x12, 0x08, 0x76, 0x3e, 0xdf, 0xf9, 0xfc, 0x9d, 0xef, 0x9c, 0xf1, 0x1c, 0xc3, 0xde, 0x98,
	0x08, 0x7f, 0x42, 0x30, 0xcb, 0x7c, 0x8e, 0xdb, 0x19, 0xc5, 0xa9, 0xc0, 0x93, 0x38, 0x6b, 0x8f,
	0xb3, 0xe7, 0xfc, 0x23, 0xfd, 0xd4, 0xa6, 0x2c, 0x13, 0x59, 0x9b, 0xb3, 0xb8, 0x2d, 0x58, 0x38,
	0x1a, 0x91, 0x78, 0x48, 0xb3, 0x09, 0x89, 0x2f, 0x7d, 0x95, 0x40, 0x6b, 0xf3, 0xe8, 0xe6, 0x37,
	0x80, 0xff, 0xf7, 0xb3, 0x74, 0x44, 0xc6, 0x39, 0xc3, 0xc9, 0x7b, 0x9d, 0xec, 0xa9, 0x1c, 0x72,
	0xa1, 0x4e, 0xd2, 0x28, 0xcb, 0xd3, 0xc4, 0xb5, 0x36, 0xac, 0xd6, 0x72, 0x50, 0x84, 0xc8, 0x83,
	0xa5, 0x2c, 0x17, 0x3a, 0xb5, 0xa0, 0x52, 0xd3, 0x18, 0xed, 0x81, 0x7d, 0x9e, 0x71, 0xd7, 0xde,
	0xb0, 0x5a, 0x4e, 0xe7, 0x99, 0x5f, 0x71, 0xf1, 0x97, 0x5a, 0x7e, 0xff, 0x68, 0x10, 0xc8, 0xf7,
	0x50, 0x08, 0xc8, 0x54, 0x19, 0x72, 0x11, 0x0a, 0xc2, 0x05, 0x89, 0xb9, 0xfb, 0x8f, 0x52, 0xeb,
	0xdc, 0x54, 0x6d, 0x30, 0x7d, 0x33, 0xf8, 0xd7, 0xa8, 0xcd, 0x20, 0xef, 0x87, 0x05, 0x76, 0xff,
	0x68, 0x80, 0xd6, 0x61, 0xf1, 0x3c, 0xc7, 0x39, 0x56, 0xdd, 0xd9, 0x81, 0x0e, 0xd0, 0x01, 0xd4,
	0xf9, 0x49, 0x48, 0x49, 0x3a, 0x56, 0xad, 0x39, 0x9d, 0x9d, 0x5b, 0xf4, 0xe0, 0x0f, 0xf4, 0xab,
	0x41, 0xa1, 0xe1, 0xf5, 0xa1, 0x6e, 0x30, 0xd4, 0x04, 0x3b, 0x26, 0x4c, 0x55, 0xb3, 0x02, 0xf9,
	0x28, 0x11, 0x4a, 0x98, 0xaa, 0x63, 0x05, 0xf2, 0x51, 0x71, 0x22, 0x3d, 0x3d, 0xc9, 0x89, 0xb8,
	0xe2, 0x44, 0x7a, 0x02, 0x92, 0x13, 0x71, 0xef, 0x57, 0x0d, 0x60, 0xd6, 0x0e, 0xda, 0x86, 0xca,
	0xa1, 0x9a, 0xd3, 0x5a, 0x15, 0x73, 0xa7, 0xf9, 0x08, 0x1c, 0x96, 0x4f, 0xf0, 0x30, 0xcd, 0xcf,
	0x22, 0xac, 0x6b, 0xda, 0x01, 0x48, 0xe8, 0x50, 0x21, 0xe8, 0x3f, 0xa8, 0xc9, 0x89, 0xe7, 0xba,
	0xfa, 0x72, 0x60, 0x22, 0x79, 0xd8, 0x24, 0x15, 0x98, 0x5d, 0x84, 0x13, 0xe5, 0xc2, 0x0e, 0xa6,
	0x31, 0xc2, 0xe0, 0xc4, 0x93, 0x90, 0x73, 0x32, 0x22, 0x98, 0x71, 0x77, 0x71, 0xc3, 0x6e, 0x39,
	0x9d, 0xfd, 0xdb, 0x1f, 0x93, 0xbf, 0x3f, 0x53, 0x79, 0x93, 0x0a, 0x76, 0x19, 0x94, 0x75, 0xbd,
	0xcf, 0xd0, 0xac, 0x12, 0xe4, 0x5c, 0x4e, 0x71, 0xd1, 0xab, 0x7c, 0x44, 0x03, 0x58, 0xbc, 0x08,
	0x27, 0x39, 0x36, 0xe7, 0xb6, 0x77, 0x27, 0x1b, 0x81, 0xd6, 0x7a, 0xb5, 0xb0, 0x6b, 0x79, 0xbf,
	0x6d, 0x80, 0x59, 0x06, 0x3d, 0x04, 0x98, 0x99, 0x33, 0x06, 0x4a, 0x88, 0x1c, 0x58, 0x84, 0x4f,
	0xc2, 0x0b, 0x92, 0xb1, 0xe2, 0x76, 0x14, 0xb1, 0xfc, 0xe6, 0xa2, 0x2c, 0x64, 0x89, 0x99, 0xb1,
	0x0e, 0x50, 0x02, 0xf5, 0x33, 0x2c, 0x98, 0xfe, 0xd2, 0xe5, 0x08, 0xdf, 0xdd, 0xc9, 0xbb, 0x7f,
	0xa0, 0xc5, 0xf4, 0x24, 0x0b, 0x69, 0xef, 0x8b, 0x05, 0x2b, 0xe5, 0xcc, 0x35, 0x23, 0x3c, 0x9e,
	0x1f, 0xe1, 0xeb, 0xfb, 0xb0, 0x51, 0x9e, 0xe4, 0x77, 0x0b, 0x6a, 0x1a, 0x45, 0x27, 0x50, 0x53,
	0x38, 0x77, 0x2d, 0xd5, 0x72, 0xef, 0x3e, 0x6a, 0xf9, 0x1f, 0x94, 0xa4, 0x6e, 0xdc, 0xe8, 0x7b,
	0x2f, 0xc1, 0x29, 0xc1, 0xd7, 0x74, 0xbd, 0x5e, 0xee, 0xda, 0x2a, 0xf9, 0xdd, 0xfc, 0x69, 0xeb,
	0x55, 0x71, 0x08, 0x4d, 0xb5, 0x1d, 0xca, 0x3b, 0x49, 0xdb, 0xde, 0xaa, 0xda, 0x96, 0x5b, 0xa0,
	0x2f, 0xb9, 0xa5, 0x25, 0xd4, 0x38, 0x9f, 0x07, 0xbc, 0xaf, 0x36, 0x34, 0x2a, 0x24, 0xf4, 0x00,
	0x96, 0x74, 0x0d, 0x92, 0x98, 0x8d, 0x54, 0x57, 0xf1, 0xdb, 0xa4, 0xd8, 0x1c, 0x0b, 0x57, 0x36,
	0x87, 0x3d, 0xdb, 0x1c, 0xdb, 0xb0, 0x46, 0x43, 0xce, 0x71, 0x32, 0xa4, 0x61, 0x7c, 0x8a, 0x05,
	0x37, 0x97, 0x75, 0x55, 0xa3, 0x3d, 0x0d, 0xa2, 0x27, 0xd0, 0x30, 0x34, 0x16, 0x0a, 0x3c, 0xa4,
	0x54, 0xde, 0x5a, 0x29, 0x62, 0x78, 0x41, 0x28, 0x70, 0x8f, 0x72, 0xf4, 0x18, 0x56, 0x0c, 0x2f,
	0xba, 0x14, 0x98, 0xbb, 0x35, 0x25, 0xe6, 0x68, 0xac, 0x2b, 0xa1, 0xaa, 0x54, 0x44, 0xb9, 0x5b,
	0xaf, 0x4a, 0x75, 0x29, 0x47, 0x4f, 0xa1, 0x91, 0xb0, 0x8c, 0xd2, 0x92, 0xb5, 0x25, 0xa5, 0xb6,
	0x66, 0xe0, 0xc2, 0x5b, 0x0b, 0x9a, 0x05, 0x71, 0x6a, 0x6e, 0x59, 0x29, 0x16, 0xcc, 0xc2, 0xdd,
	0x16, 0xac, 0x16, 0x4c, 0x6d, 0x0f, 0x94, 0xe0, 0x8a, 0x01, 0xb5, 0xbf, 0xaa, 0x9c, 0x34, 0xe8,
	0x5c, 0x91, 0xeb, 0x52, 0xde, 0xdd, 0x3d, 0x7e, 0x71, 0xa3, 0xdf, 0xea, 0x38, 0xab, 0xfc, 0x55,
	0xa3, 0x9a, 0x4a, 0xec, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0x28, 0x81, 0x12, 0x05, 0x97, 0x07,
	0x00, 0x00,
}
