version: "3"
services: 
  nats-1:
    command:
      - "-DV"
      - "-p"
      - "4222"
    expose:
      - "6222"
    image: "nats:latest"
    ports:
      - "4222:4222"

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  dnc-dispatcher:
    image: registry.opentelco.io/go-dnc:latest
    volumes:
      - ./dnc-config-docker.hcl:/dnc/config.hcl:z
    command: ["dispatcher", "start", "-c", "/dnc/config.hcl"]
    networks:
      dnc:
      nats:
      mongodb:

  dnc-poller:
    image: registry.opentelco.io/go-dnc:latest
    volumes:
      - ./dnc-config-docker.hcl:/dnc/config.hcl:z
    command: ["poller", "start", "-c", "/dnc/config.hcl"]
    networks:
      dnc:
      nats:
      mongodb:


networks:
  nats:
  mongodb:
  dnc:


volumes:
  mongodb_data_container:
