version: "3"
services: 
  nats-1: 
    command: 
      - "-DV"
      - "-p"
      - "4222"
      - "-cluster"
      - "nats://172.25.255.10:6222"
    expose:
      - "6222"
    image: "nats:latest"
    networks: 
      nats: 
        ipv4_address: "172.25.255.10"
    ports:
      - "14222:4222"
    labels:
     - "traefik.frontend.rule=Host:nats.docker.localhost"
    
  nats-2: 
    command: 
      - "-DV"
      - "-p"
      - "4222"
      - "-cluster"
      - "nats://172.25.255.20:6222"
      - "-routes"
      - "nats://172.25.255.10:6222"
    image: "nats:latest"
    expose:
      - "6222"
    networks: 
      nats: 
        ipv4_address: "172.25.255.20"
    ports:
      - "24222:4222"
    labels:
     - "traefik.frontend.rule=Host:nats.docker.localhost"

  nats-3: 
    command: 
      - "-DV"
      - "-p"
      - "4222"
      - "-cluster"
      - "nats://172.25.255.30:6222"
      - "-routes"
      - "nats://172.25.255.10:6222"
    image: "nats:latest"
    expose:
      - "6222"
    networks: 
      nats: 
        ipv4_address: "172.25.255.30"
    ports:
      - "34222:4222"
    labels:
     - "traefik.frontend.rule=Host:nats.docker.localhost"      
  
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      mongodb:

  swpx:
    image: internal.registry.opentelco.io/go-swpx:latest
    ports: 
      - 1337:1337
    networks:
      nats:
      mongodb:
      
  dnc-dispatcher-1:
    image: internal.registry.opentelco.io/go-dnc:latest
    volumes:
      - ./config-docker-sait.hcl:/dnc/config.hcl:z
    command:
      /dnc/go-dnc dispatcher start -c /dnc/config.hcl
    networks:
      dnc:
      nats:
      mongodb:
  
  dnc-dispatcher-2:
    image: internal.registry.opentelco.io/go-dnc:latest
    volumes:
      - ./config-docker-sait.hcl:/dnc/config.hcl:z
    command:
      /dnc/go-dnc dispatcher start -c /dnc/config.hcl
    networks:
      dnc:
      nats:
      mongodb:
      

  dnc-poller-1:
    image: internal.registry.opentelco.io/go-dnc:latest
    volumes:
      - ./config-docker-sait.hcl:/dnc/config.hcl:z
    command:
      /dnc/go-dnc poller start -c /dnc/config.hcl
    networks:
      dnc:
      nats:
      mongodb:

  dnc-poller-2:
    image: internal.registry.opentelco.io/go-dnc:latest
    volumes:
      - ./config-docker-sait.hcl:/dnc/config.hcl:z
    command:
      /dnc/go-dnc poller start -c /dnc/config.hcl
    networks:
      dnc:
      nats:
      mongodb:

  dnc-poller-3:
    image: internal.registry.opentelco.io/go-dnc:latest
    volumes:
      - ./config-docker-sait.hcl:/dnc/config.hcl:z
    command:
      /dnc/go-dnc poller start -c /dnc/config.hcl
    networks:
      dnc:
      nats:
      mongodb:


networks: 
  nats: 
    external: 
      name: nats
  mongodb: 
    external: 
      name: mongodb
  dnc: 
    external: 
      name: dnc
    
volumes:
  mongodb_data_container:

