version: "3"
services: 
  nats-1: 
    command: 
      - "-DV"
      - "-p"
      - "4222"
    expose:
      - "6222"
    image: "nats:latest"
    ports:
      - "4222:4222"

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db



volumes:
  mongodb_data_container:
