snmp:
  community: xWTyZ9nA158ktJF2
  timeout: 20s
  version: 2
  retries: 3
  dynamic_repetitions: true
interface_cache:
  server: mongodb://10.102.11.110:27027
  database: swpx
  collection: interface_cache
  timeout_seconds: 30
response_cache:
  server: mongodb://10.102.11.110:27027
  database: swpx
  collection: response_cache
  timeout_seconds: 30
nats:
  event_servers: ['nats://10.201.11.120:14222', 'nats://10.201.11.121:24222', 'nats://10.201.11.122:34222']
telnet:
  username: "root-telnet"
  password: "qwerty1234"
  port: 23
  screen_length: "0"
  screen_length_command: "screen-length %s temporary"
  default_prompt: "\\n[<\\[](\\S+)[>#\\]]$"
  default_errors: "error|failed|unrecognized"
  ttl: "30s"
  read_dead_line: "8s"
  write_dead_line: "8s"