snmp:
  community: xWTyZ9nA158ktJF2
  timeout: 20s
  version: 2
  retries: 3
  dynamic_repetitions: true
mongo:
  server: mongodb://localhost:27017
  database: test
  collection: cache
  timeout_seconds: 30
nats:
  event_servers: ['nats://localhost:14222', 'nats://localhost:24222', 'nats://localhost:34222']