default_provider: "vx"
dnc_server_addr: "localhost:1339"

snmp:
  community: xWTyZ9nA158ktJF2
  timeout: 20s
  version: 2
  retries: 3
  port: 161
  dynamic_repetitions: true

interface_cache:
  server: mongodb://localhost:27019
  database: test
  collection: interface_cache
  timeout_seconds: 30

response_cache:
  server: mongodb://localhost:27017
  database: test
  collection: response_cache
  timeout_seconds: 30


ssh:
  username: ""
  password: ""
  port: 22
  screen_length: "0"
  screen_length_command: "screen-length 0 temporary"
  default_prompt: "\\n[<\\[](\\S+)[>#\\]]$"
  default_errors: "error|failed|unrecognized"
  ttl: "30s"
  read_dead_line: "8s"
  write_dead_line: "8s"
#  ssh_key_path: "/home/ardi/.ssh/id_rsa"
telnet:
  username: ""
  password: ""
  port: 23
  screen_length: "0"
  screen_length_command: "screen-length 0 temporary"
  default_prompt: "\\n[<\\[](\\S+)[>#\\]]$"
  default_errors: "error|failed|unrecognized"
  ttl: "30s"
  read_dead_line: "180s"
  write_dead_line: "180s"
