// Code generated by protoc-gen-go. DO NOT EDIT.
// source: git.liero.se/opentelco/go-swpx/proto/resource/resource.proto

package resource

import (
	context "context"
	fmt "fmt"
	networkelement "git.liero.se/opentelco/go-swpx/proto/networkelement"
	provider "git.liero.se/opentelco/go-swpx/proto/provider"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_478d904e0b4d43a1, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type VersionResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_478d904e0b4d43a1, []int{1}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type TechnicalInformationResponse struct {
	NetworkElement       *networkelement.Element     `protobuf:"bytes,1,opt,name=network_element,json=networkElement,proto3" json:"network_element,omitempty"`
	PhysicalPort         string                      `protobuf:"bytes,2,opt,name=physical_port,json=physicalPort,proto3" json:"physical_port,omitempty"`
	Transceiver          *networkelement.Transceiver `protobuf:"bytes,3,opt,name=transceiver,proto3" json:"transceiver,omitempty"`
	Error                *Error                      `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	RequestObjectID      string                      `protobuf:"bytes,5,opt,name=RequestObjectID,proto3" json:"RequestObjectID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *TechnicalInformationResponse) Reset()         { *m = TechnicalInformationResponse{} }
func (m *TechnicalInformationResponse) String() string { return proto.CompactTextString(m) }
func (*TechnicalInformationResponse) ProtoMessage()    {}
func (*TechnicalInformationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_478d904e0b4d43a1, []int{2}
}

func (m *TechnicalInformationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TechnicalInformationResponse.Unmarshal(m, b)
}
func (m *TechnicalInformationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TechnicalInformationResponse.Marshal(b, m, deterministic)
}
func (m *TechnicalInformationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TechnicalInformationResponse.Merge(m, src)
}
func (m *TechnicalInformationResponse) XXX_Size() int {
	return xxx_messageInfo_TechnicalInformationResponse.Size(m)
}
func (m *TechnicalInformationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TechnicalInformationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TechnicalInformationResponse proto.InternalMessageInfo

func (m *TechnicalInformationResponse) GetNetworkElement() *networkelement.Element {
	if m != nil {
		return m.NetworkElement
	}
	return nil
}

func (m *TechnicalInformationResponse) GetPhysicalPort() string {
	if m != nil {
		return m.PhysicalPort
	}
	return ""
}

func (m *TechnicalInformationResponse) GetTransceiver() *networkelement.Transceiver {
	if m != nil {
		return m.Transceiver
	}
	return nil
}

func (m *TechnicalInformationResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *TechnicalInformationResponse) GetRequestObjectID() string {
	if m != nil {
		return m.RequestObjectID
	}
	return ""
}

type Status struct {
	Error                bool     `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_478d904e0b4d43a1, []int{3}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Error struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_478d904e0b4d43a1, []int{4}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

// used in request
type NetworkElement struct {
	Hostname             string                  `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip                   string                  `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Interface            string                  `protobuf:"bytes,3,opt,name=interface,proto3" json:"interface,omitempty"`
	InterfaceIndex       int64                   `protobuf:"varint,4,opt,name=interface_index,json=interfaceIndex,proto3" json:"interface_index,omitempty"`
	PhysicalIndex        int64                   `protobuf:"varint,5,opt,name=physical_index,json=physicalIndex,proto3" json:"physical_index,omitempty"`
	Conf                 *provider.Configuration `protobuf:"bytes,6,opt,name=conf,proto3" json:"conf,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *NetworkElement) Reset()         { *m = NetworkElement{} }
func (m *NetworkElement) String() string { return proto.CompactTextString(m) }
func (*NetworkElement) ProtoMessage()    {}
func (*NetworkElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_478d904e0b4d43a1, []int{5}
}

func (m *NetworkElement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkElement.Unmarshal(m, b)
}
func (m *NetworkElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkElement.Marshal(b, m, deterministic)
}
func (m *NetworkElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkElement.Merge(m, src)
}
func (m *NetworkElement) XXX_Size() int {
	return xxx_messageInfo_NetworkElement.Size(m)
}
func (m *NetworkElement) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkElement.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkElement proto.InternalMessageInfo

func (m *NetworkElement) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *NetworkElement) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *NetworkElement) GetInterface() string {
	if m != nil {
		return m.Interface
	}
	return ""
}

func (m *NetworkElement) GetInterfaceIndex() int64 {
	if m != nil {
		return m.InterfaceIndex
	}
	return 0
}

func (m *NetworkElement) GetPhysicalIndex() int64 {
	if m != nil {
		return m.PhysicalIndex
	}
	return 0
}

func (m *NetworkElement) GetConf() *provider.Configuration {
	if m != nil {
		return m.Conf
	}
	return nil
}

type TechnicalInformationRequest struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port                 string   `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	Provider             string   `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	Driver               string   `protobuf:"bytes,4,opt,name=driver,proto3" json:"driver,omitempty"`
	Region               string   `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	Timeout              int32    `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	RecreateIndex        bool     `protobuf:"varint,7,opt,name=recreate_index,json=recreateIndex,proto3" json:"recreate_index,omitempty"`
	CacheTtl             int32    `protobuf:"varint,8,opt,name=cache_ttl,json=cacheTtl,proto3" json:"cache_ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TechnicalInformationRequest) Reset()         { *m = TechnicalInformationRequest{} }
func (m *TechnicalInformationRequest) String() string { return proto.CompactTextString(m) }
func (*TechnicalInformationRequest) ProtoMessage()    {}
func (*TechnicalInformationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_478d904e0b4d43a1, []int{6}
}

func (m *TechnicalInformationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TechnicalInformationRequest.Unmarshal(m, b)
}
func (m *TechnicalInformationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TechnicalInformationRequest.Marshal(b, m, deterministic)
}
func (m *TechnicalInformationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TechnicalInformationRequest.Merge(m, src)
}
func (m *TechnicalInformationRequest) XXX_Size() int {
	return xxx_messageInfo_TechnicalInformationRequest.Size(m)
}
func (m *TechnicalInformationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TechnicalInformationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TechnicalInformationRequest proto.InternalMessageInfo

func (m *TechnicalInformationRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *TechnicalInformationRequest) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *TechnicalInformationRequest) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *TechnicalInformationRequest) GetDriver() string {
	if m != nil {
		return m.Driver
	}
	return ""
}

func (m *TechnicalInformationRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *TechnicalInformationRequest) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *TechnicalInformationRequest) GetRecreateIndex() bool {
	if m != nil {
		return m.RecreateIndex
	}
	return false
}

func (m *TechnicalInformationRequest) GetCacheTtl() int32 {
	if m != nil {
		return m.CacheTtl
	}
	return 0
}

type NetworkElementInterface struct {
	Index                int64    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Alias                string   `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkElementInterface) Reset()         { *m = NetworkElementInterface{} }
func (m *NetworkElementInterface) String() string { return proto.CompactTextString(m) }
func (*NetworkElementInterface) ProtoMessage()    {}
func (*NetworkElementInterface) Descriptor() ([]byte, []int) {
	return fileDescriptor_478d904e0b4d43a1, []int{7}
}

func (m *NetworkElementInterface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkElementInterface.Unmarshal(m, b)
}
func (m *NetworkElementInterface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkElementInterface.Marshal(b, m, deterministic)
}
func (m *NetworkElementInterface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkElementInterface.Merge(m, src)
}
func (m *NetworkElementInterface) XXX_Size() int {
	return xxx_messageInfo_NetworkElementInterface.Size(m)
}
func (m *NetworkElementInterface) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkElementInterface.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkElementInterface proto.InternalMessageInfo

func (m *NetworkElementInterface) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *NetworkElementInterface) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *NetworkElementInterface) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

// map port to entire interface for faster retrieval
type NetworkElementInterfaces struct {
	Interfaces           map[string]*NetworkElementInterface `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *NetworkElementInterfaces) Reset()         { *m = NetworkElementInterfaces{} }
func (m *NetworkElementInterfaces) String() string { return proto.CompactTextString(m) }
func (*NetworkElementInterfaces) ProtoMessage()    {}
func (*NetworkElementInterfaces) Descriptor() ([]byte, []int) {
	return fileDescriptor_478d904e0b4d43a1, []int{8}
}

func (m *NetworkElementInterfaces) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkElementInterfaces.Unmarshal(m, b)
}
func (m *NetworkElementInterfaces) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkElementInterfaces.Marshal(b, m, deterministic)
}
func (m *NetworkElementInterfaces) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkElementInterfaces.Merge(m, src)
}
func (m *NetworkElementInterfaces) XXX_Size() int {
	return xxx_messageInfo_NetworkElementInterfaces.Size(m)
}
func (m *NetworkElementInterfaces) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkElementInterfaces.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkElementInterfaces proto.InternalMessageInfo

func (m *NetworkElementInterfaces) GetInterfaces() map[string]*NetworkElementInterface {
	if m != nil {
		return m.Interfaces
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "resource.Empty")
	proto.RegisterType((*VersionResponse)(nil), "resource.VersionResponse")
	proto.RegisterType((*TechnicalInformationResponse)(nil), "resource.TechnicalInformationResponse")
	proto.RegisterType((*Status)(nil), "resource.Status")
	proto.RegisterType((*Error)(nil), "resource.Error")
	proto.RegisterType((*NetworkElement)(nil), "resource.NetworkElement")
	proto.RegisterType((*TechnicalInformationRequest)(nil), "resource.TechnicalInformationRequest")
	proto.RegisterType((*NetworkElementInterface)(nil), "resource.NetworkElementInterface")
	proto.RegisterType((*NetworkElementInterfaces)(nil), "resource.NetworkElementInterfaces")
	proto.RegisterMapType((map[string]*NetworkElementInterface)(nil), "resource.NetworkElementInterfaces.InterfacesEntry")
}

func init() {
	proto.RegisterFile("git.liero.se/opentelco/go-swpx/proto/resource/resource.proto", fileDescriptor_478d904e0b4d43a1)
}

var fileDescriptor_478d904e0b4d43a1 = []byte{
	// 781 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0x97, 0x93, 0x3a, 0x7f, 0x5e, 0x76, 0x13, 0x18, 0x55, 0xd4, 0x9b, 0xf6, 0x50, 0x8c, 0x0a,
	0x95, 0x56, 0x9b, 0x48, 0x41, 0x2b, 0x10, 0x02, 0x09, 0x01, 0x11, 0x8a, 0x44, 0x61, 0x19, 0x2a,
	0x0e, 0x5c, 0x52, 0xd7, 0x79, 0x49, 0x86, 0x3a, 0x1e, 0x33, 0x33, 0x49, 0x9b, 0x23, 0x07, 0x3e,
	0x02, 0xdf, 0x8b, 0x1b, 0x1f, 0x85, 0x2b, 0x9a, 0x3f, 0x76, 0x9c, 0xa8, 0x49, 0x41, 0x7b, 0xf2,
	0x7b, 0xbf, 0xf9, 0xcd, 0xfb, 0x3f, 0xcf, 0xf0, 0xf9, 0x8c, 0xa9, 0x5e, 0xc2, 0x50, 0xf0, 0x9e,
	0xc4, 0x3e, 0xcf, 0x30, 0x55, 0x98, 0xc4, 0xbc, 0x3f, 0xe3, 0xaf, 0xe4, 0x7d, 0xf6, 0xd0, 0xcf,
	0x04, 0x57, 0xbc, 0x2f, 0x50, 0xf2, 0xa5, 0x88, 0xb1, 0x10, 0x7a, 0x06, 0x27, 0x8d, 0x5c, 0xef,
	0x9e, 0xa5, 0xa8, 0xee, 0xb9, 0xb8, 0xc3, 0x04, 0x17, 0x98, 0xaa, 0xbe, 0xfb, 0x5a, 0x5e, 0xf7,
	0x24, 0x13, 0x7c, 0xc5, 0x26, 0x28, 0xfa, 0xb9, 0x60, 0x0f, 0xc2, 0x3a, 0xf8, 0xc3, 0x45, 0xa6,
	0xd6, 0xe1, 0x4b, 0xe8, 0xfc, 0x8c, 0x42, 0x32, 0x9e, 0x52, 0x94, 0x19, 0x4f, 0x25, 0x92, 0x00,
	0xea, 0x2b, 0x0b, 0x05, 0xde, 0xb9, 0x77, 0xd9, 0xa4, 0xb9, 0x1a, 0xfe, 0x59, 0x81, 0xb3, 0x6b,
	0x8c, 0xe7, 0x29, 0x8b, 0xa3, 0x64, 0x94, 0x4e, 0xb9, 0x58, 0x44, 0xaa, 0x7c, 0xf5, 0x4b, 0xe8,
	0xb8, 0x78, 0xc6, 0x2e, 0x10, 0x63, 0xa2, 0x35, 0x38, 0xe9, 0x6d, 0xc7, 0xd9, 0x1b, 0xda, 0x2f,
	0x6d, 0x3b, 0xdc, 0xe9, 0xe4, 0x03, 0x78, 0x9e, 0xcd, 0xd7, 0x52, 0x3b, 0x18, 0x67, 0x5c, 0xa8,
	0xa0, 0x62, 0x42, 0x78, 0x96, 0x83, 0x6f, 0xb8, 0x50, 0xe4, 0x0b, 0x68, 0x29, 0x11, 0xa5, 0x32,
	0x46, 0xb6, 0x42, 0x11, 0x54, 0x8d, 0x8b, 0xd3, 0x5d, 0x17, 0xd7, 0x1b, 0x0a, 0x2d, 0xf3, 0xc9,
	0x05, 0xf8, 0x28, 0x04, 0x17, 0xc1, 0x91, 0xb9, 0xd8, 0xe9, 0x15, 0xd5, 0x1d, 0x6a, 0x98, 0xda,
	0x53, 0x72, 0x09, 0x1d, 0x8a, 0xbf, 0x2d, 0x51, 0xaa, 0x1f, 0x6e, 0x7f, 0xc5, 0x58, 0x8d, 0xbe,
	0x09, 0x7c, 0x13, 0xcc, 0x2e, 0x1c, 0xde, 0x40, 0xed, 0x27, 0x15, 0xa9, 0xa5, 0x24, 0xc7, 0xb9,
	0x69, 0x9d, 0x76, 0x23, 0xb7, 0x44, 0xe0, 0x28, 0xe6, 0x13, 0x34, 0xb9, 0xf8, 0xd4, 0xc8, 0x1a,
	0x53, 0xeb, 0x0c, 0x4d, 0xf0, 0x4d, 0x6a, 0x64, 0x5d, 0xf9, 0x05, 0x4a, 0x19, 0xcd, 0xd0, 0x84,
	0xd6, 0xa4, 0xb9, 0x1a, 0xbe, 0x06, 0xdf, 0xc4, 0x56, 0xa6, 0x78, 0x5b, 0x94, 0xc7, 0x9c, 0x84,
	0x7f, 0x7b, 0xd0, 0xfe, 0x7e, 0xbb, 0xc0, 0x5d, 0x68, 0xcc, 0xb9, 0x54, 0x69, 0xb4, 0xc8, 0x2d,
	0x14, 0x3a, 0x69, 0x43, 0x85, 0x65, 0xae, 0xe2, 0x15, 0x96, 0x91, 0x33, 0x68, 0xb2, 0x54, 0xa1,
	0x98, 0x46, 0x71, 0x1e, 0xe8, 0x06, 0x20, 0x1f, 0x41, 0xa7, 0x50, 0xc6, 0x2c, 0x9d, 0xe0, 0x83,
	0x89, 0xba, 0x4a, 0xdb, 0x05, 0x3c, 0xd2, 0x28, 0xb9, 0x80, 0x76, 0xd1, 0x53, 0xcb, 0xf3, 0x0d,
	0xaf, 0xe8, 0xb4, 0xa5, 0xbd, 0xd4, 0x09, 0xa4, 0xd3, 0xa0, 0xe6, 0x26, 0xa6, 0x18, 0xd9, 0xaf,
	0x79, 0x3a, 0x65, 0xb3, 0xa5, 0xb0, 0xb3, 0x66, 0x48, 0xe1, 0x3f, 0x1e, 0x9c, 0x3e, 0x3e, 0x8a,
	0xa6, 0x35, 0x07, 0xd3, 0x24, 0x70, 0x54, 0x1a, 0x2d, 0x23, 0x6b, 0x7e, 0xee, 0xcf, 0x65, 0x5a,
	0xe8, 0xe4, 0x3d, 0xa8, 0x4d, 0x84, 0x99, 0x34, 0xdb, 0x15, 0xa7, 0x69, 0x5c, 0xe0, 0x4c, 0xbf,
	0x13, 0x3b, 0x17, 0x4e, 0xd3, 0x3d, 0x52, 0x6c, 0x81, 0x7c, 0xa9, 0x4c, 0x2e, 0x3e, 0xcd, 0x55,
	0x5d, 0x09, 0x81, 0xb1, 0xc0, 0x48, 0xe5, 0x15, 0xab, 0x9b, 0x39, 0x79, 0x9e, 0xa3, 0xb6, 0x12,
	0xa7, 0xd0, 0x8c, 0xa3, 0x78, 0x8e, 0x63, 0xa5, 0x92, 0xa0, 0x61, 0x4c, 0x34, 0x0c, 0x70, 0xad,
	0x92, 0x70, 0x06, 0x27, 0xdb, 0x2d, 0x1d, 0x15, 0x1d, 0x39, 0x06, 0xdf, 0x5a, 0xf5, 0x4c, 0x7d,
	0xad, 0x42, 0xce, 0xa1, 0x35, 0x41, 0x19, 0x0b, 0x96, 0xe9, 0x02, 0xb9, 0xac, 0xcb, 0x90, 0xbe,
	0x17, 0x25, 0x2c, 0x92, 0x2e, 0x73, 0xab, 0x84, 0x7f, 0x79, 0x10, 0xec, 0xf1, 0x24, 0x09, 0x05,
	0x28, 0xba, 0x2c, 0x03, 0xef, 0xbc, 0x7a, 0xd9, 0x1a, 0x0c, 0x36, 0x0f, 0x69, 0xdf, 0xbd, 0xde,
	0x46, 0x1c, 0xa6, 0x4a, 0xac, 0x69, 0xc9, 0x4a, 0xf7, 0x06, 0x3a, 0x3b, 0xc7, 0xe4, 0x1d, 0xa8,
	0xde, 0xe1, 0xda, 0x75, 0x50, 0x8b, 0xe4, 0x13, 0xf0, 0x57, 0x51, 0xb2, 0xb4, 0x73, 0xde, 0x1a,
	0xbc, 0xff, 0xa4, 0x4f, 0x6a, 0xf9, 0x9f, 0x55, 0x3e, 0xf5, 0x06, 0xbf, 0x7b, 0x70, 0xfc, 0xd8,
	0xd4, 0x10, 0x06, 0x41, 0x81, 0xeb, 0x15, 0x53, 0x3e, 0xbb, 0xd8, 0xb8, 0x38, 0x30, 0x71, 0xdd,
	0x0f, 0x9f, 0xa2, 0xd9, 0x1d, 0x39, 0xf8, 0xa3, 0x0a, 0x0d, 0xea, 0x98, 0xe4, 0x35, 0xd4, 0xdd,
	0xfa, 0x25, 0xe5, 0x35, 0xa4, 0x57, 0x73, 0xf7, 0xc5, 0x06, 0xd8, 0x5d, 0xd1, 0x57, 0x07, 0xc2,
	0x0d, 0xf6, 0x55, 0xa4, 0xbb, 0x6f, 0x09, 0x93, 0xef, 0xe0, 0xd9, 0x55, 0x94, 0x6d, 0xe6, 0x68,
	0xbf, 0x89, 0xf0, 0xe9, 0x16, 0x93, 0x1f, 0xe1, 0xdd, 0xab, 0x28, 0x1b, 0xa6, 0x8a, 0xa9, 0xf5,
	0x1b, 0xf7, 0xc2, 0xdf, 0xd2, 0x24, 0x85, 0x17, 0xdf, 0xa2, 0x2a, 0x2d, 0xf4, 0xff, 0x96, 0xf0,
	0xa1, 0x5f, 0xc2, 0x57, 0xfd, 0x5f, 0x5e, 0xfd, 0xaf, 0x7f, 0xf0, 0x6d, 0xcd, 0xe8, 0x1f, 0xff,
	0x1b, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x98, 0xe0, 0x2b, 0xbb, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TechnicalInformationClient is the client API for TechnicalInformation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TechnicalInformationClient interface {
	TechnicalPortInformation(ctx context.Context, in *TechnicalInformationRequest, opts ...grpc.CallOption) (*TechnicalInformationResponse, error)
}

type technicalInformationClient struct {
	cc grpc.ClientConnInterface
}

func NewTechnicalInformationClient(cc grpc.ClientConnInterface) TechnicalInformationClient {
	return &technicalInformationClient{cc}
}

func (c *technicalInformationClient) TechnicalPortInformation(ctx context.Context, in *TechnicalInformationRequest, opts ...grpc.CallOption) (*TechnicalInformationResponse, error) {
	out := new(TechnicalInformationResponse)
	err := c.cc.Invoke(ctx, "/resource.TechnicalInformation/TechnicalPortInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TechnicalInformationServer is the server API for TechnicalInformation service.
type TechnicalInformationServer interface {
	TechnicalPortInformation(context.Context, *TechnicalInformationRequest) (*TechnicalInformationResponse, error)
}

// UnimplementedTechnicalInformationServer can be embedded to have forward compatible implementations.
type UnimplementedTechnicalInformationServer struct {
}

func (*UnimplementedTechnicalInformationServer) TechnicalPortInformation(ctx context.Context, req *TechnicalInformationRequest) (*TechnicalInformationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TechnicalPortInformation not implemented")
}

func RegisterTechnicalInformationServer(s *grpc.Server, srv TechnicalInformationServer) {
	s.RegisterService(&_TechnicalInformation_serviceDesc, srv)
}

func _TechnicalInformation_TechnicalPortInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TechnicalInformationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TechnicalInformationServer).TechnicalPortInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resource.TechnicalInformation/TechnicalPortInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TechnicalInformationServer).TechnicalPortInformation(ctx, req.(*TechnicalInformationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TechnicalInformation_serviceDesc = grpc.ServiceDesc{
	ServiceName: "resource.TechnicalInformation",
	HandlerType: (*TechnicalInformationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TechnicalPortInformation",
			Handler:    _TechnicalInformation_TechnicalPortInformation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "git.liero.se/opentelco/go-swpx/proto/resource/resource.proto",
}

// ResourceClient is the client API for Resource service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResourceClient interface {
	Version(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VersionResponse, error)
	TechnicalPortInformation(ctx context.Context, in *NetworkElement, opts ...grpc.CallOption) (*networkelement.Element, error)
	MapInterface(ctx context.Context, in *NetworkElement, opts ...grpc.CallOption) (*NetworkElementInterfaces, error)
	MapEntityPhysical(ctx context.Context, in *NetworkElement, opts ...grpc.CallOption) (*NetworkElementInterfaces, error)
	GetTransceiverInformation(ctx context.Context, in *NetworkElement, opts ...grpc.CallOption) (*networkelement.Transceiver, error)
}

type resourceClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceClient(cc grpc.ClientConnInterface) ResourceClient {
	return &resourceClient{cc}
}

func (c *resourceClient) Version(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/resource.Resource/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceClient) TechnicalPortInformation(ctx context.Context, in *NetworkElement, opts ...grpc.CallOption) (*networkelement.Element, error) {
	out := new(networkelement.Element)
	err := c.cc.Invoke(ctx, "/resource.Resource/TechnicalPortInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceClient) MapInterface(ctx context.Context, in *NetworkElement, opts ...grpc.CallOption) (*NetworkElementInterfaces, error) {
	out := new(NetworkElementInterfaces)
	err := c.cc.Invoke(ctx, "/resource.Resource/MapInterface", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceClient) MapEntityPhysical(ctx context.Context, in *NetworkElement, opts ...grpc.CallOption) (*NetworkElementInterfaces, error) {
	out := new(NetworkElementInterfaces)
	err := c.cc.Invoke(ctx, "/resource.Resource/MapEntityPhysical", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceClient) GetTransceiverInformation(ctx context.Context, in *NetworkElement, opts ...grpc.CallOption) (*networkelement.Transceiver, error) {
	out := new(networkelement.Transceiver)
	err := c.cc.Invoke(ctx, "/resource.Resource/GetTransceiverInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceServer is the server API for Resource service.
type ResourceServer interface {
	Version(context.Context, *Empty) (*VersionResponse, error)
	TechnicalPortInformation(context.Context, *NetworkElement) (*networkelement.Element, error)
	MapInterface(context.Context, *NetworkElement) (*NetworkElementInterfaces, error)
	MapEntityPhysical(context.Context, *NetworkElement) (*NetworkElementInterfaces, error)
	GetTransceiverInformation(context.Context, *NetworkElement) (*networkelement.Transceiver, error)
}

// UnimplementedResourceServer can be embedded to have forward compatible implementations.
type UnimplementedResourceServer struct {
}

func (*UnimplementedResourceServer) Version(ctx context.Context, req *Empty) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (*UnimplementedResourceServer) TechnicalPortInformation(ctx context.Context, req *NetworkElement) (*networkelement.Element, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TechnicalPortInformation not implemented")
}
func (*UnimplementedResourceServer) MapInterface(ctx context.Context, req *NetworkElement) (*NetworkElementInterfaces, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MapInterface not implemented")
}
func (*UnimplementedResourceServer) MapEntityPhysical(ctx context.Context, req *NetworkElement) (*NetworkElementInterfaces, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MapEntityPhysical not implemented")
}
func (*UnimplementedResourceServer) GetTransceiverInformation(ctx context.Context, req *NetworkElement) (*networkelement.Transceiver, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransceiverInformation not implemented")
}

func RegisterResourceServer(s *grpc.Server, srv ResourceServer) {
	s.RegisterService(&_Resource_serviceDesc, srv)
}

func _Resource_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resource.Resource/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServer).Version(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resource_TechnicalPortInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkElement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServer).TechnicalPortInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resource.Resource/TechnicalPortInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServer).TechnicalPortInformation(ctx, req.(*NetworkElement))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resource_MapInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkElement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServer).MapInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resource.Resource/MapInterface",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServer).MapInterface(ctx, req.(*NetworkElement))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resource_MapEntityPhysical_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkElement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServer).MapEntityPhysical(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resource.Resource/MapEntityPhysical",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServer).MapEntityPhysical(ctx, req.(*NetworkElement))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resource_GetTransceiverInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkElement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServer).GetTransceiverInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resource.Resource/GetTransceiverInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServer).GetTransceiverInformation(ctx, req.(*NetworkElement))
	}
	return interceptor(ctx, in, info, handler)
}

var _Resource_serviceDesc = grpc.ServiceDesc{
	ServiceName: "resource.Resource",
	HandlerType: (*ResourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _Resource_Version_Handler,
		},
		{
			MethodName: "TechnicalPortInformation",
			Handler:    _Resource_TechnicalPortInformation_Handler,
		},
		{
			MethodName: "MapInterface",
			Handler:    _Resource_MapInterface_Handler,
		},
		{
			MethodName: "MapEntityPhysical",
			Handler:    _Resource_MapEntityPhysical_Handler,
		},
		{
			MethodName: "GetTransceiverInformation",
			Handler:    _Resource_GetTransceiverInformation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "git.liero.se/opentelco/go-swpx/proto/resource/resource.proto",
}
