// Code generated by protoc-gen-go. DO NOT EDIT.
// source: git.liero.se/opentelco/go-swpx/proto/resource/resource.proto

package resource

import (
	context "context"
	fmt "fmt"
	networkelement "git.liero.se/opentelco/go-swpx/proto/networkelement"
	provider "git.liero.se/opentelco/go-swpx/proto/provider"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_478d904e0b4d43a1, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type VersionResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_478d904e0b4d43a1, []int{1}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type TechnicalPortInformationResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TechnicalPortInformationResponse) Reset()         { *m = TechnicalPortInformationResponse{} }
func (m *TechnicalPortInformationResponse) String() string { return proto.CompactTextString(m) }
func (*TechnicalPortInformationResponse) ProtoMessage()    {}
func (*TechnicalPortInformationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_478d904e0b4d43a1, []int{2}
}

func (m *TechnicalPortInformationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TechnicalPortInformationResponse.Unmarshal(m, b)
}
func (m *TechnicalPortInformationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TechnicalPortInformationResponse.Marshal(b, m, deterministic)
}
func (m *TechnicalPortInformationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TechnicalPortInformationResponse.Merge(m, src)
}
func (m *TechnicalPortInformationResponse) XXX_Size() int {
	return xxx_messageInfo_TechnicalPortInformationResponse.Size(m)
}
func (m *TechnicalPortInformationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TechnicalPortInformationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TechnicalPortInformationResponse proto.InternalMessageInfo

func (m *TechnicalPortInformationResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

// used in request
type NetworkElement struct {
	Hostname             string                  `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip                   string                  `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Interface            string                  `protobuf:"bytes,3,opt,name=interface,proto3" json:"interface,omitempty"`
	InterfaceIndex       int64                   `protobuf:"varint,4,opt,name=interface_index,json=interfaceIndex,proto3" json:"interface_index,omitempty"`
	PhysicalIndex        int64                   `protobuf:"varint,5,opt,name=physical_index,json=physicalIndex,proto3" json:"physical_index,omitempty"`
	Conf                 *provider.Configuration `protobuf:"bytes,6,opt,name=conf,proto3" json:"conf,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *NetworkElement) Reset()         { *m = NetworkElement{} }
func (m *NetworkElement) String() string { return proto.CompactTextString(m) }
func (*NetworkElement) ProtoMessage()    {}
func (*NetworkElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_478d904e0b4d43a1, []int{3}
}

func (m *NetworkElement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkElement.Unmarshal(m, b)
}
func (m *NetworkElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkElement.Marshal(b, m, deterministic)
}
func (m *NetworkElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkElement.Merge(m, src)
}
func (m *NetworkElement) XXX_Size() int {
	return xxx_messageInfo_NetworkElement.Size(m)
}
func (m *NetworkElement) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkElement.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkElement proto.InternalMessageInfo

func (m *NetworkElement) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *NetworkElement) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *NetworkElement) GetInterface() string {
	if m != nil {
		return m.Interface
	}
	return ""
}

func (m *NetworkElement) GetInterfaceIndex() int64 {
	if m != nil {
		return m.InterfaceIndex
	}
	return 0
}

func (m *NetworkElement) GetPhysicalIndex() int64 {
	if m != nil {
		return m.PhysicalIndex
	}
	return 0
}

func (m *NetworkElement) GetConf() *provider.Configuration {
	if m != nil {
		return m.Conf
	}
	return nil
}

type NetworkElementInterface struct {
	Index                int64    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Alias                string   `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkElementInterface) Reset()         { *m = NetworkElementInterface{} }
func (m *NetworkElementInterface) String() string { return proto.CompactTextString(m) }
func (*NetworkElementInterface) ProtoMessage()    {}
func (*NetworkElementInterface) Descriptor() ([]byte, []int) {
	return fileDescriptor_478d904e0b4d43a1, []int{4}
}

func (m *NetworkElementInterface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkElementInterface.Unmarshal(m, b)
}
func (m *NetworkElementInterface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkElementInterface.Marshal(b, m, deterministic)
}
func (m *NetworkElementInterface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkElementInterface.Merge(m, src)
}
func (m *NetworkElementInterface) XXX_Size() int {
	return xxx_messageInfo_NetworkElementInterface.Size(m)
}
func (m *NetworkElementInterface) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkElementInterface.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkElementInterface proto.InternalMessageInfo

func (m *NetworkElementInterface) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *NetworkElementInterface) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *NetworkElementInterface) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

type NetworkElementInterfaces struct {
	Interfaces           []*NetworkElementInterface `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *NetworkElementInterfaces) Reset()         { *m = NetworkElementInterfaces{} }
func (m *NetworkElementInterfaces) String() string { return proto.CompactTextString(m) }
func (*NetworkElementInterfaces) ProtoMessage()    {}
func (*NetworkElementInterfaces) Descriptor() ([]byte, []int) {
	return fileDescriptor_478d904e0b4d43a1, []int{5}
}

func (m *NetworkElementInterfaces) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkElementInterfaces.Unmarshal(m, b)
}
func (m *NetworkElementInterfaces) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkElementInterfaces.Marshal(b, m, deterministic)
}
func (m *NetworkElementInterfaces) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkElementInterfaces.Merge(m, src)
}
func (m *NetworkElementInterfaces) XXX_Size() int {
	return xxx_messageInfo_NetworkElementInterfaces.Size(m)
}
func (m *NetworkElementInterfaces) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkElementInterfaces.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkElementInterfaces proto.InternalMessageInfo

func (m *NetworkElementInterfaces) GetInterfaces() []*NetworkElementInterface {
	if m != nil {
		return m.Interfaces
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "resource.Empty")
	proto.RegisterType((*VersionResponse)(nil), "resource.VersionResponse")
	proto.RegisterType((*TechnicalPortInformationResponse)(nil), "resource.TechnicalPortInformationResponse")
	proto.RegisterType((*NetworkElement)(nil), "resource.NetworkElement")
	proto.RegisterType((*NetworkElementInterface)(nil), "resource.NetworkElementInterface")
	proto.RegisterType((*NetworkElementInterfaces)(nil), "resource.NetworkElementInterfaces")
}

func init() {
	proto.RegisterFile("git.liero.se/opentelco/go-swpx/proto/resource/resource.proto", fileDescriptor_478d904e0b4d43a1)
}

var fileDescriptor_478d904e0b4d43a1 = []byte{
	// 483 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xdd, 0x8a, 0xd3, 0x40,
	0x18, 0x25, 0xed, 0x76, 0xbb, 0xfb, 0x55, 0x5b, 0x1c, 0x84, 0xce, 0xc6, 0xbd, 0x88, 0x01, 0xb1,
	0xb0, 0x6c, 0x02, 0x15, 0xef, 0x44, 0x50, 0x29, 0x52, 0xb0, 0xb2, 0x86, 0xc5, 0x0b, 0x41, 0x24,
	0xa6, 0x5f, 0xdb, 0xc1, 0x74, 0x66, 0x98, 0x99, 0xed, 0x6e, 0x1f, 0xc0, 0x67, 0xf4, 0x75, 0x24,
	0x99, 0x64, 0xda, 0x2d, 0x04, 0x15, 0xaf, 0x32, 0xe7, 0xe4, 0x7c, 0x3f, 0x67, 0x72, 0x08, 0xbc,
	0x5a, 0x32, 0x13, 0xe5, 0x0c, 0x95, 0x88, 0x34, 0xc6, 0x42, 0x22, 0x37, 0x98, 0x67, 0x22, 0x5e,
	0x8a, 0x4b, 0x7d, 0x2b, 0xef, 0x62, 0xa9, 0x84, 0x11, 0xb1, 0x42, 0x2d, 0x6e, 0x54, 0x86, 0xee,
	0x10, 0x95, 0x3c, 0x39, 0xa9, 0xb1, 0x7f, 0xce, 0xd1, 0xdc, 0x0a, 0xf5, 0x03, 0x73, 0x5c, 0x23,
	0x37, 0x71, 0xf5, 0xb4, 0x3a, 0x7f, 0x28, 0x95, 0xd8, 0xb0, 0x39, 0xaa, 0xb8, 0x3e, 0xd8, 0x17,
	0x61, 0x17, 0x3a, 0x93, 0xb5, 0x34, 0xdb, 0xf0, 0x02, 0x06, 0x9f, 0x51, 0x69, 0x26, 0x78, 0x82,
	0x5a, 0x0a, 0xae, 0x91, 0x50, 0xe8, 0x6e, 0x2c, 0x45, 0xbd, 0xc0, 0x1b, 0x9d, 0x26, 0x35, 0x0c,
	0x5f, 0x43, 0x70, 0x8d, 0xd9, 0x8a, 0xb3, 0x2c, 0xcd, 0xaf, 0x84, 0x32, 0x53, 0xbe, 0x10, 0x6a,
	0x9d, 0x9a, 0xfd, 0x6a, 0x1f, 0x8a, 0xe5, 0xca, 0x73, 0x55, 0xee, 0x70, 0xf8, 0xcb, 0x83, 0xfe,
	0x47, 0xbb, 0xef, 0xc4, 0xee, 0x59, 0xc8, 0x57, 0x42, 0x1b, 0x9e, 0xae, 0x9d, 0xbc, 0xc6, 0xa4,
	0x0f, 0x2d, 0x26, 0x69, 0xab, 0x64, 0x5b, 0x4c, 0x92, 0x73, 0x38, 0x65, 0xdc, 0xa0, 0x5a, 0xa4,
	0x19, 0xd2, 0x76, 0x49, 0xef, 0x08, 0xf2, 0x1c, 0x06, 0x0e, 0x7c, 0x63, 0x7c, 0x8e, 0x77, 0xf4,
	0x28, 0xf0, 0x46, 0xed, 0xa4, 0xef, 0xe8, 0x69, 0xc1, 0x92, 0x67, 0xd0, 0x97, 0xab, 0xad, 0x2e,
	0x4c, 0x54, 0xba, 0x4e, 0xa9, 0x7b, 0x58, 0xb3, 0x56, 0x76, 0x01, 0x47, 0x99, 0xe0, 0x0b, 0x7a,
	0x1c, 0x78, 0xa3, 0xde, 0x78, 0x18, 0xb9, 0x1b, 0x7c, 0x27, 0xf8, 0x82, 0x2d, 0x6f, 0x94, 0xf5,
	0x5d, 0x8a, 0xc2, 0x25, 0x0c, 0xef, 0x1b, 0x9b, 0xba, 0xbd, 0x1e, 0x43, 0xc7, 0x4e, 0xf1, 0xca,
	0x29, 0x16, 0x90, 0x00, 0x7a, 0x73, 0xd4, 0x99, 0x62, 0xb2, 0xe8, 0x52, 0x99, 0xdc, 0xa7, 0x8a,
	0xba, 0x34, 0x67, 0xa9, 0xae, 0x9c, 0x5a, 0x10, 0x7e, 0x05, 0xda, 0x30, 0x48, 0x93, 0x37, 0x00,
	0xce, 0xaa, 0xa6, 0x5e, 0xd0, 0x1e, 0xf5, 0xc6, 0x4f, 0x23, 0x17, 0x9d, 0x86, 0xba, 0x64, 0xaf,
	0x68, 0xfc, 0xb3, 0x0d, 0x27, 0x49, 0x55, 0x40, 0x5e, 0x42, 0xb7, 0xca, 0x06, 0x19, 0xec, 0xda,
	0x94, 0xb9, 0xf1, 0xcf, 0x76, 0xc4, 0x61, 0x7e, 0x66, 0x40, 0x9b, 0x52, 0x42, 0x68, 0xd3, 0x3a,
	0xfe, 0x30, 0xba, 0x9f, 0xe4, 0xa8, 0x4e, 0xc8, 0x07, 0x78, 0x30, 0x4b, 0xe5, 0xee, 0x3e, 0x9b,
	0x5b, 0x84, 0x7f, 0xf4, 0xaa, 0xc9, 0x27, 0x78, 0x34, 0x4b, 0xe5, 0x84, 0x1b, 0x66, 0xb6, 0x57,
	0xd5, 0xf7, 0xfe, 0xcf, 0x96, 0x09, 0x9c, 0xbd, 0x47, 0x73, 0xad, 0x52, 0xae, 0x33, 0x64, 0x1b,
	0x54, 0x7f, 0x67, 0xf8, 0xc9, 0xa1, 0xe1, 0xbd, 0x0e, 0x6f, 0xe3, 0x2f, 0x97, 0xff, 0xf4, 0x83,
	0xf8, 0x7e, 0x5c, 0xe2, 0x17, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb4, 0xf0, 0x72, 0xe2, 0x58,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ResourceClient is the client API for Resource service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResourceClient interface {
	Version(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VersionResponse, error)
	TechnicalPortInformation(ctx context.Context, in *NetworkElement, opts ...grpc.CallOption) (*networkelement.Element, error)
	MapInterface(ctx context.Context, in *NetworkElement, opts ...grpc.CallOption) (*NetworkElementInterfaces, error)
	MapEntityPhysical(ctx context.Context, in *NetworkElement, opts ...grpc.CallOption) (*NetworkElementInterfaces, error)
	GetTransceiverInformation(ctx context.Context, in *NetworkElement, opts ...grpc.CallOption) (*networkelement.Transceiver, error)
}

type resourceClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceClient(cc grpc.ClientConnInterface) ResourceClient {
	return &resourceClient{cc}
}

func (c *resourceClient) Version(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/resource.Resource/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceClient) TechnicalPortInformation(ctx context.Context, in *NetworkElement, opts ...grpc.CallOption) (*networkelement.Element, error) {
	out := new(networkelement.Element)
	err := c.cc.Invoke(ctx, "/resource.Resource/TechnicalPortInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceClient) MapInterface(ctx context.Context, in *NetworkElement, opts ...grpc.CallOption) (*NetworkElementInterfaces, error) {
	out := new(NetworkElementInterfaces)
	err := c.cc.Invoke(ctx, "/resource.Resource/MapInterface", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceClient) MapEntityPhysical(ctx context.Context, in *NetworkElement, opts ...grpc.CallOption) (*NetworkElementInterfaces, error) {
	out := new(NetworkElementInterfaces)
	err := c.cc.Invoke(ctx, "/resource.Resource/MapEntityPhysical", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceClient) GetTransceiverInformation(ctx context.Context, in *NetworkElement, opts ...grpc.CallOption) (*networkelement.Transceiver, error) {
	out := new(networkelement.Transceiver)
	err := c.cc.Invoke(ctx, "/resource.Resource/GetTransceiverInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceServer is the server API for Resource service.
type ResourceServer interface {
	Version(context.Context, *Empty) (*VersionResponse, error)
	TechnicalPortInformation(context.Context, *NetworkElement) (*networkelement.Element, error)
	MapInterface(context.Context, *NetworkElement) (*NetworkElementInterfaces, error)
	MapEntityPhysical(context.Context, *NetworkElement) (*NetworkElementInterfaces, error)
	GetTransceiverInformation(context.Context, *NetworkElement) (*networkelement.Transceiver, error)
}

// UnimplementedResourceServer can be embedded to have forward compatible implementations.
type UnimplementedResourceServer struct {
}

func (*UnimplementedResourceServer) Version(ctx context.Context, req *Empty) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (*UnimplementedResourceServer) TechnicalPortInformation(ctx context.Context, req *NetworkElement) (*networkelement.Element, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TechnicalPortInformation not implemented")
}
func (*UnimplementedResourceServer) MapInterface(ctx context.Context, req *NetworkElement) (*NetworkElementInterfaces, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MapInterface not implemented")
}
func (*UnimplementedResourceServer) MapEntityPhysical(ctx context.Context, req *NetworkElement) (*NetworkElementInterfaces, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MapEntityPhysical not implemented")
}
func (*UnimplementedResourceServer) GetTransceiverInformation(ctx context.Context, req *NetworkElement) (*networkelement.Transceiver, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransceiverInformation not implemented")
}

func RegisterResourceServer(s *grpc.Server, srv ResourceServer) {
	s.RegisterService(&_Resource_serviceDesc, srv)
}

func _Resource_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resource.Resource/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServer).Version(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resource_TechnicalPortInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkElement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServer).TechnicalPortInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resource.Resource/TechnicalPortInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServer).TechnicalPortInformation(ctx, req.(*NetworkElement))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resource_MapInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkElement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServer).MapInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resource.Resource/MapInterface",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServer).MapInterface(ctx, req.(*NetworkElement))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resource_MapEntityPhysical_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkElement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServer).MapEntityPhysical(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resource.Resource/MapEntityPhysical",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServer).MapEntityPhysical(ctx, req.(*NetworkElement))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resource_GetTransceiverInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkElement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServer).GetTransceiverInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resource.Resource/GetTransceiverInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServer).GetTransceiverInformation(ctx, req.(*NetworkElement))
	}
	return interceptor(ctx, in, info, handler)
}

var _Resource_serviceDesc = grpc.ServiceDesc{
	ServiceName: "resource.Resource",
	HandlerType: (*ResourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _Resource_Version_Handler,
		},
		{
			MethodName: "TechnicalPortInformation",
			Handler:    _Resource_TechnicalPortInformation_Handler,
		},
		{
			MethodName: "MapInterface",
			Handler:    _Resource_MapInterface_Handler,
		},
		{
			MethodName: "MapEntityPhysical",
			Handler:    _Resource_MapEntityPhysical_Handler,
		},
		{
			MethodName: "GetTransceiverInformation",
			Handler:    _Resource_GetTransceiverInformation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "git.liero.se/opentelco/go-swpx/proto/resource/resource.proto",
}
