// Code generated by protoc-gen-go. DO NOT EDIT.
// source: git.liero.se/opentelco/go-swpx/proto/provider/provider.proto

package provider

import (
	context "context"
	fmt "fmt"
	dnc "git.liero.se/opentelco/go-swpx/proto/dnc"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_c90e022f12f82725, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type NameResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NameResponse) Reset()         { *m = NameResponse{} }
func (m *NameResponse) String() string { return proto.CompactTextString(m) }
func (*NameResponse) ProtoMessage()    {}
func (*NameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c90e022f12f82725, []int{1}
}

func (m *NameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameResponse.Unmarshal(m, b)
}
func (m *NameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameResponse.Marshal(b, m, deterministic)
}
func (m *NameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameResponse.Merge(m, src)
}
func (m *NameResponse) XXX_Size() int {
	return xxx_messageInfo_NameResponse.Size(m)
}
func (m *NameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NameResponse proto.InternalMessageInfo

func (m *NameResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type VersionResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c90e022f12f82725, []int{2}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type MatchRequest struct {
	OriginId             string   `protobuf:"bytes,1,opt,name=origin_id,json=originId,proto3" json:"origin_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MatchRequest) Reset()         { *m = MatchRequest{} }
func (m *MatchRequest) String() string { return proto.CompactTextString(m) }
func (*MatchRequest) ProtoMessage()    {}
func (*MatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c90e022f12f82725, []int{3}
}

func (m *MatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchRequest.Unmarshal(m, b)
}
func (m *MatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchRequest.Marshal(b, m, deterministic)
}
func (m *MatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchRequest.Merge(m, src)
}
func (m *MatchRequest) XXX_Size() int {
	return xxx_messageInfo_MatchRequest.Size(m)
}
func (m *MatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MatchRequest proto.InternalMessageInfo

func (m *MatchRequest) GetOriginId() string {
	if m != nil {
		return m.OriginId
	}
	return ""
}

type MatchResponse struct {
	Match                bool     `protobuf:"varint,1,opt,name=match,proto3" json:"match,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MatchResponse) Reset()         { *m = MatchResponse{} }
func (m *MatchResponse) String() string { return proto.CompactTextString(m) }
func (*MatchResponse) ProtoMessage()    {}
func (*MatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c90e022f12f82725, []int{4}
}

func (m *MatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchResponse.Unmarshal(m, b)
}
func (m *MatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchResponse.Marshal(b, m, deterministic)
}
func (m *MatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchResponse.Merge(m, src)
}
func (m *MatchResponse) XXX_Size() int {
	return xxx_messageInfo_MatchResponse.Size(m)
}
func (m *MatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MatchResponse proto.InternalMessageInfo

func (m *MatchResponse) GetMatch() bool {
	if m != nil {
		return m.Match
	}
	return false
}

type WeightResponse struct {
	Weight               int64    `protobuf:"varint,1,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WeightResponse) Reset()         { *m = WeightResponse{} }
func (m *WeightResponse) String() string { return proto.CompactTextString(m) }
func (*WeightResponse) ProtoMessage()    {}
func (*WeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c90e022f12f82725, []int{5}
}

func (m *WeightResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeightResponse.Unmarshal(m, b)
}
func (m *WeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeightResponse.Marshal(b, m, deterministic)
}
func (m *WeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeightResponse.Merge(m, src)
}
func (m *WeightResponse) XXX_Size() int {
	return xxx_messageInfo_WeightResponse.Size(m)
}
func (m *WeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WeightResponse proto.InternalMessageInfo

func (m *WeightResponse) GetWeight() int64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type ConfigTelnet struct {
	User                 string   `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=Port,proto3" json:"Port,omitempty"`
	ScreenLength         string   `protobuf:"bytes,4,opt,name=ScreenLength,proto3" json:"ScreenLength,omitempty"`
	ScreenLengthCommand  string   `protobuf:"bytes,5,opt,name=ScreenLengthCommand,proto3" json:"ScreenLengthCommand,omitempty"`
	RegexPrompt          string   `protobuf:"bytes,6,opt,name=RegexPrompt,proto3" json:"RegexPrompt,omitempty"`
	Errors               string   `protobuf:"bytes,7,opt,name=Errors,proto3" json:"Errors,omitempty"`
	TTL                  uint64   `protobuf:"varint,8,opt,name=TTL,proto3" json:"TTL,omitempty"`
	ReadDeadLine         uint64   `protobuf:"varint,9,opt,name=ReadDeadLine,proto3" json:"ReadDeadLine,omitempty"`
	WriteDeadLine        uint64   `protobuf:"varint,10,opt,name=WriteDeadLine,proto3" json:"WriteDeadLine,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigTelnet) Reset()         { *m = ConfigTelnet{} }
func (m *ConfigTelnet) String() string { return proto.CompactTextString(m) }
func (*ConfigTelnet) ProtoMessage()    {}
func (*ConfigTelnet) Descriptor() ([]byte, []int) {
	return fileDescriptor_c90e022f12f82725, []int{6}
}

func (m *ConfigTelnet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigTelnet.Unmarshal(m, b)
}
func (m *ConfigTelnet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigTelnet.Marshal(b, m, deterministic)
}
func (m *ConfigTelnet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigTelnet.Merge(m, src)
}
func (m *ConfigTelnet) XXX_Size() int {
	return xxx_messageInfo_ConfigTelnet.Size(m)
}
func (m *ConfigTelnet) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigTelnet.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigTelnet proto.InternalMessageInfo

func (m *ConfigTelnet) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ConfigTelnet) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ConfigTelnet) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ConfigTelnet) GetScreenLength() string {
	if m != nil {
		return m.ScreenLength
	}
	return ""
}

func (m *ConfigTelnet) GetScreenLengthCommand() string {
	if m != nil {
		return m.ScreenLengthCommand
	}
	return ""
}

func (m *ConfigTelnet) GetRegexPrompt() string {
	if m != nil {
		return m.RegexPrompt
	}
	return ""
}

func (m *ConfigTelnet) GetErrors() string {
	if m != nil {
		return m.Errors
	}
	return ""
}

func (m *ConfigTelnet) GetTTL() uint64 {
	if m != nil {
		return m.TTL
	}
	return 0
}

func (m *ConfigTelnet) GetReadDeadLine() uint64 {
	if m != nil {
		return m.ReadDeadLine
	}
	return 0
}

func (m *ConfigTelnet) GetWriteDeadLine() uint64 {
	if m != nil {
		return m.WriteDeadLine
	}
	return 0
}

type ConfigSSH struct {
	User                 string   `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=Port,proto3" json:"Port,omitempty"`
	ScreenLength         string   `protobuf:"bytes,4,opt,name=ScreenLength,proto3" json:"ScreenLength,omitempty"`
	ScreenLengthCommand  string   `protobuf:"bytes,5,opt,name=ScreenLengthCommand,proto3" json:"ScreenLengthCommand,omitempty"`
	RegexPrompt          string   `protobuf:"bytes,6,opt,name=RegexPrompt,proto3" json:"RegexPrompt,omitempty"`
	Errors               string   `protobuf:"bytes,7,opt,name=Errors,proto3" json:"Errors,omitempty"`
	TTL                  uint64   `protobuf:"varint,8,opt,name=TTL,proto3" json:"TTL,omitempty"`
	ReadDeadLine         uint64   `protobuf:"varint,9,opt,name=ReadDeadLine,proto3" json:"ReadDeadLine,omitempty"`
	WriteDeadLine        uint64   `protobuf:"varint,10,opt,name=WriteDeadLine,proto3" json:"WriteDeadLine,omitempty"`
	SSHKeyPath           string   `protobuf:"bytes,11,opt,name=SSHKeyPath,proto3" json:"SSHKeyPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigSSH) Reset()         { *m = ConfigSSH{} }
func (m *ConfigSSH) String() string { return proto.CompactTextString(m) }
func (*ConfigSSH) ProtoMessage()    {}
func (*ConfigSSH) Descriptor() ([]byte, []int) {
	return fileDescriptor_c90e022f12f82725, []int{7}
}

func (m *ConfigSSH) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigSSH.Unmarshal(m, b)
}
func (m *ConfigSSH) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigSSH.Marshal(b, m, deterministic)
}
func (m *ConfigSSH) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigSSH.Merge(m, src)
}
func (m *ConfigSSH) XXX_Size() int {
	return xxx_messageInfo_ConfigSSH.Size(m)
}
func (m *ConfigSSH) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigSSH.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigSSH proto.InternalMessageInfo

func (m *ConfigSSH) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ConfigSSH) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ConfigSSH) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ConfigSSH) GetScreenLength() string {
	if m != nil {
		return m.ScreenLength
	}
	return ""
}

func (m *ConfigSSH) GetScreenLengthCommand() string {
	if m != nil {
		return m.ScreenLengthCommand
	}
	return ""
}

func (m *ConfigSSH) GetRegexPrompt() string {
	if m != nil {
		return m.RegexPrompt
	}
	return ""
}

func (m *ConfigSSH) GetErrors() string {
	if m != nil {
		return m.Errors
	}
	return ""
}

func (m *ConfigSSH) GetTTL() uint64 {
	if m != nil {
		return m.TTL
	}
	return 0
}

func (m *ConfigSSH) GetReadDeadLine() uint64 {
	if m != nil {
		return m.ReadDeadLine
	}
	return 0
}

func (m *ConfigSSH) GetWriteDeadLine() uint64 {
	if m != nil {
		return m.WriteDeadLine
	}
	return 0
}

func (m *ConfigSSH) GetSSHKeyPath() string {
	if m != nil {
		return m.SSHKeyPath
	}
	return ""
}

type ConfigSNMP struct {
	Community            string   `protobuf:"bytes,1,opt,name=Community,proto3" json:"Community,omitempty"`
	Version              uint32   `protobuf:"varint,2,opt,name=Version,proto3" json:"Version,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=Port,proto3" json:"Port,omitempty"`
	Timeout              uint64   `protobuf:"varint,4,opt,name=Timeout,proto3" json:"Timeout,omitempty"`
	Retries              int32    `protobuf:"varint,5,opt,name=Retries,proto3" json:"Retries,omitempty"`
	MaxIterations        int32    `protobuf:"varint,6,opt,name=MaxIterations,proto3" json:"MaxIterations,omitempty"`
	MaxRepetitions       int32    `protobuf:"varint,7,opt,name=MaxRepetitions,proto3" json:"MaxRepetitions,omitempty"`
	NonRepeaters         int32    `protobuf:"varint,8,opt,name=NonRepeaters,proto3" json:"NonRepeaters,omitempty"`
	DynamicRepetitions   bool     `protobuf:"varint,9,opt,name=DynamicRepetitions,proto3" json:"DynamicRepetitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigSNMP) Reset()         { *m = ConfigSNMP{} }
func (m *ConfigSNMP) String() string { return proto.CompactTextString(m) }
func (*ConfigSNMP) ProtoMessage()    {}
func (*ConfigSNMP) Descriptor() ([]byte, []int) {
	return fileDescriptor_c90e022f12f82725, []int{8}
}

func (m *ConfigSNMP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigSNMP.Unmarshal(m, b)
}
func (m *ConfigSNMP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigSNMP.Marshal(b, m, deterministic)
}
func (m *ConfigSNMP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigSNMP.Merge(m, src)
}
func (m *ConfigSNMP) XXX_Size() int {
	return xxx_messageInfo_ConfigSNMP.Size(m)
}
func (m *ConfigSNMP) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigSNMP.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigSNMP proto.InternalMessageInfo

func (m *ConfigSNMP) GetCommunity() string {
	if m != nil {
		return m.Community
	}
	return ""
}

func (m *ConfigSNMP) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ConfigSNMP) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ConfigSNMP) GetTimeout() uint64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *ConfigSNMP) GetRetries() int32 {
	if m != nil {
		return m.Retries
	}
	return 0
}

func (m *ConfigSNMP) GetMaxIterations() int32 {
	if m != nil {
		return m.MaxIterations
	}
	return 0
}

func (m *ConfigSNMP) GetMaxRepetitions() int32 {
	if m != nil {
		return m.MaxRepetitions
	}
	return 0
}

func (m *ConfigSNMP) GetNonRepeaters() int32 {
	if m != nil {
		return m.NonRepeaters
	}
	return 0
}

func (m *ConfigSNMP) GetDynamicRepetitions() bool {
	if m != nil {
		return m.DynamicRepetitions
	}
	return false
}

type Configuration struct {
	SNMP                 *ConfigSNMP   `protobuf:"bytes,1,opt,name=SNMP,proto3" json:"SNMP,omitempty"`
	Telnet               *ConfigTelnet `protobuf:"bytes,2,opt,name=Telnet,proto3" json:"Telnet,omitempty"`
	Ssh                  *ConfigSSH    `protobuf:"bytes,3,opt,name=Ssh,proto3" json:"Ssh,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Configuration) Reset()         { *m = Configuration{} }
func (m *Configuration) String() string { return proto.CompactTextString(m) }
func (*Configuration) ProtoMessage()    {}
func (*Configuration) Descriptor() ([]byte, []int) {
	return fileDescriptor_c90e022f12f82725, []int{9}
}

func (m *Configuration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Configuration.Unmarshal(m, b)
}
func (m *Configuration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Configuration.Marshal(b, m, deterministic)
}
func (m *Configuration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Configuration.Merge(m, src)
}
func (m *Configuration) XXX_Size() int {
	return xxx_messageInfo_Configuration.Size(m)
}
func (m *Configuration) XXX_DiscardUnknown() {
	xxx_messageInfo_Configuration.DiscardUnknown(m)
}

var xxx_messageInfo_Configuration proto.InternalMessageInfo

func (m *Configuration) GetSNMP() *ConfigSNMP {
	if m != nil {
		return m.SNMP
	}
	return nil
}

func (m *Configuration) GetTelnet() *ConfigTelnet {
	if m != nil {
		return m.Telnet
	}
	return nil
}

func (m *Configuration) GetSsh() *ConfigSSH {
	if m != nil {
		return m.Ssh
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "provider.Empty")
	proto.RegisterType((*NameResponse)(nil), "provider.NameResponse")
	proto.RegisterType((*VersionResponse)(nil), "provider.VersionResponse")
	proto.RegisterType((*MatchRequest)(nil), "provider.MatchRequest")
	proto.RegisterType((*MatchResponse)(nil), "provider.MatchResponse")
	proto.RegisterType((*WeightResponse)(nil), "provider.WeightResponse")
	proto.RegisterType((*ConfigTelnet)(nil), "provider.configTelnet")
	proto.RegisterType((*ConfigSSH)(nil), "provider.configSSH")
	proto.RegisterType((*ConfigSNMP)(nil), "provider.configSNMP")
	proto.RegisterType((*Configuration)(nil), "provider.Configuration")
}

func init() {
	proto.RegisterFile("git.liero.se/opentelco/go-swpx/proto/provider/provider.proto", fileDescriptor_c90e022f12f82725)
}

var fileDescriptor_c90e022f12f82725 = []byte{
	// 717 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x55, 0xcd, 0x6e, 0xda, 0x4a,
	0x14, 0x16, 0x3f, 0xe6, 0xe7, 0x00, 0x49, 0x34, 0x89, 0x72, 0x7d, 0xb9, 0x57, 0x57, 0xc8, 0xba,
	0xa9, 0x90, 0xa2, 0x40, 0x4b, 0x54, 0xa9, 0x8b, 0xac, 0x9a, 0x44, 0x4d, 0x54, 0x88, 0xd0, 0x40,
	0x1b, 0xa9, 0x9b, 0xca, 0xc5, 0xa7, 0x30, 0x6a, 0x3c, 0xe3, 0x8e, 0x87, 0x04, 0xde, 0xa2, 0x4f,
	0xd2, 0x47, 0xe8, 0x43, 0x74, 0xdb, 0x97, 0xa9, 0x66, 0x6c, 0x83, 0x0d, 0xd9, 0x64, 0xdf, 0x0d,
	0x9a, 0xef, 0x3b, 0xdf, 0x19, 0x9f, 0xf3, 0x59, 0xfe, 0x80, 0xb3, 0x29, 0x53, 0x9d, 0x3b, 0x86,
	0x52, 0x74, 0x42, 0xec, 0x8a, 0x00, 0xb9, 0xc2, 0xbb, 0x89, 0xe8, 0x4e, 0xc5, 0x49, 0xf8, 0x10,
	0x2c, 0xba, 0x81, 0x14, 0x4a, 0xe8, 0xdf, 0x7b, 0xe6, 0xa1, 0x5c, 0x1d, 0x3a, 0x86, 0x27, 0x95,
	0x04, 0x37, 0x1b, 0x1e, 0x9f, 0x74, 0x3d, 0x3e, 0x89, 0x0a, 0x4e, 0x19, 0xac, 0x4b, 0x3f, 0x50,
	0x4b, 0xc7, 0x81, 0xfa, 0x8d, 0xeb, 0x23, 0xc5, 0x30, 0x10, 0x3c, 0x44, 0x42, 0xa0, 0xc8, 0x5d,
	0x1f, 0xed, 0x5c, 0x2b, 0xd7, 0xae, 0x52, 0x73, 0x76, 0x8e, 0x61, 0xf7, 0x3d, 0xca, 0x90, 0x09,
	0xbe, 0x92, 0xd9, 0x50, 0xbe, 0x8f, 0xa8, 0x58, 0x99, 0x40, 0xe7, 0x18, 0xea, 0x03, 0x57, 0x4d,
	0x66, 0x14, 0xbf, 0xce, 0x31, 0x54, 0xe4, 0x1f, 0xa8, 0x0a, 0xc9, 0xa6, 0x8c, 0x7f, 0x64, 0x5e,
	0xac, 0xad, 0x44, 0xc4, 0xb5, 0xe7, 0x1c, 0x41, 0x23, 0x16, 0xc7, 0xf7, 0x1e, 0x80, 0xe5, 0x6b,
	0xc2, 0x28, 0x2b, 0x34, 0x02, 0x4e, 0x1b, 0x76, 0x6e, 0x91, 0x4d, 0x67, 0x6a, 0xa5, 0x3b, 0x84,
	0xd2, 0x83, 0x61, 0x8c, 0xb0, 0x40, 0x63, 0xe4, 0xfc, 0xc8, 0x43, 0x7d, 0x22, 0xf8, 0x67, 0x36,
	0x1d, 0xe3, 0x1d, 0x47, 0xa5, 0xf7, 0x79, 0x17, 0xa2, 0x4c, 0xf6, 0xd1, 0x67, 0xd2, 0x84, 0xca,
	0xd0, 0x0d, 0xc3, 0x07, 0x21, 0x3d, 0x3b, 0x1f, 0x4d, 0x94, 0x60, 0xad, 0x1f, 0x0a, 0xa9, 0xec,
	0x42, 0x2b, 0xd7, 0xb6, 0xa8, 0x39, 0x13, 0x07, 0xea, 0xa3, 0x89, 0x44, 0xe4, 0x7d, 0xe4, 0x53,
	0x35, 0xb3, 0x8b, 0xa6, 0x27, 0xc3, 0x91, 0xe7, 0xb0, 0x9f, 0xc6, 0xe7, 0xc2, 0xf7, 0x5d, 0xee,
	0xd9, 0x96, 0x91, 0x3e, 0x56, 0x22, 0x2d, 0xa8, 0x51, 0x9c, 0xe2, 0x62, 0x28, 0x85, 0x1f, 0x28,
	0xbb, 0x64, 0x94, 0x69, 0x4a, 0x2f, 0x79, 0x29, 0xa5, 0x90, 0xa1, 0x5d, 0x36, 0xc5, 0x18, 0x91,
	0x3d, 0x28, 0x8c, 0xc7, 0x7d, 0xbb, 0xd2, 0xca, 0xb5, 0x8b, 0x54, 0x1f, 0xf5, 0x84, 0x14, 0x5d,
	0xef, 0x02, 0x5d, 0xaf, 0xcf, 0x38, 0xda, 0x55, 0x53, 0xca, 0x70, 0xe4, 0x7f, 0x68, 0xdc, 0x4a,
	0xa6, 0x70, 0x25, 0x02, 0x23, 0xca, 0x92, 0xce, 0xaf, 0x3c, 0x54, 0x23, 0x03, 0x47, 0xa3, 0xab,
	0x3f, 0xee, 0x3d, 0xcd, 0x3d, 0xf2, 0x1f, 0xc0, 0x68, 0x74, 0xf5, 0x16, 0x97, 0x43, 0x57, 0xcd,
	0xec, 0x9a, 0x79, 0x6e, 0x8a, 0x71, 0xbe, 0xe7, 0x01, 0x62, 0x77, 0x6f, 0x06, 0x43, 0xf2, 0x2f,
	0x54, 0xf5, 0x3e, 0x73, 0xce, 0xd4, 0x32, 0xf6, 0x78, 0x4d, 0xe8, 0x6f, 0x2c, 0xfe, 0xec, 0x8c,
	0xcf, 0x0d, 0x9a, 0xc0, 0x8c, 0xcd, 0x8d, 0xd8, 0x66, 0x1b, 0xca, 0x63, 0xe6, 0xa3, 0x98, 0x2b,
	0xe3, 0x70, 0x91, 0x26, 0x50, 0x57, 0x28, 0x2a, 0xc9, 0x30, 0x34, 0x86, 0x5a, 0x34, 0x81, 0x7a,
	0xa9, 0x81, 0xbb, 0xb8, 0x56, 0x28, 0x5d, 0xc5, 0x04, 0x0f, 0x8d, 0x8d, 0x16, 0xcd, 0x92, 0xe4,
	0x19, 0xec, 0x0c, 0xdc, 0x05, 0xc5, 0x00, 0x15, 0x8b, 0x64, 0x65, 0x23, 0xdb, 0x60, 0xb5, 0x8d,
	0x37, 0x3a, 0x22, 0x02, 0x74, 0x15, 0xca, 0xd0, 0x38, 0x6c, 0xd1, 0x0c, 0x47, 0x3a, 0x40, 0x2e,
	0x96, 0xdc, 0xf5, 0xd9, 0x24, 0x7d, 0x5f, 0xd5, 0x7c, 0xec, 0x8f, 0x54, 0x9c, 0x6f, 0x39, 0x68,
	0x9c, 0x1b, 0xc3, 0xe6, 0xd1, 0x38, 0xa4, 0x0d, 0x45, 0xed, 0x9d, 0xb1, 0xab, 0xd6, 0x3b, 0xe8,
	0xac, 0x12, 0x6f, 0xed, 0x2b, 0x35, 0x0a, 0xd2, 0x81, 0x52, 0x14, 0x02, 0xc6, 0xbe, 0x5a, 0xef,
	0x70, 0x53, 0x1b, 0x55, 0x69, 0xac, 0x22, 0x47, 0x50, 0x18, 0x85, 0x33, 0x63, 0x6a, 0xad, 0xb7,
	0xbf, 0x75, 0xf1, 0xe8, 0x8a, 0xea, 0x7a, 0xef, 0x67, 0x1e, 0x2a, 0xc3, 0xb8, 0x46, 0xba, 0x50,
	0xd4, 0xf1, 0x49, 0x76, 0xd7, 0x72, 0x93, 0xab, 0xcd, 0xd4, 0xc3, 0x32, 0xf9, 0xfa, 0x72, 0xf5,
	0x52, 0xb7, 0x7b, 0xfe, 0x5e, 0x13, 0x9b, 0x79, 0xfb, 0x0a, 0x2c, 0x13, 0x94, 0x24, 0x75, 0x6f,
	0x3a, 0x66, 0x9b, 0x7f, 0x6d, 0xf1, 0x71, 0xe7, 0x0b, 0x28, 0xf5, 0x85, 0xf8, 0x32, 0x0f, 0x08,
	0xe9, 0xe8, 0xfc, 0x8f, 0x40, 0xd2, 0xb6, 0x9f, 0xe1, 0xe2, 0x96, 0x53, 0x28, 0x45, 0x71, 0xbb,
	0x3d, 0xa2, 0xbd, 0x26, 0x36, 0x12, 0xf9, 0x0c, 0xf6, 0xde, 0xa0, 0xca, 0xbe, 0xab, 0xad, 0xf6,
	0xd4, 0x94, 0x19, 0xe5, 0xeb, 0xee, 0x87, 0x93, 0x27, 0xfd, 0xd1, 0x7d, 0x2a, 0x19, 0x7c, 0xfa,
	0x3b, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x71, 0xbf, 0xb4, 0x20, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProviderClient is the client API for Provider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProviderClient interface {
	Name(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NameResponse, error)
	Version(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VersionResponse, error)
	Match(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*MatchResponse, error)
	Lookup(ctx context.Context, in *dnc.LookupRequest, opts ...grpc.CallOption) (*dnc.LookupResponse, error)
	Weight(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WeightResponse, error)
	GetConfiguration(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Configuration, error)
}

type providerClient struct {
	cc grpc.ClientConnInterface
}

func NewProviderClient(cc grpc.ClientConnInterface) ProviderClient {
	return &providerClient{cc}
}

func (c *providerClient) Name(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NameResponse, error) {
	out := new(NameResponse)
	err := c.cc.Invoke(ctx, "/provider.Provider/Name", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) Version(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/provider.Provider/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) Match(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*MatchResponse, error) {
	out := new(MatchResponse)
	err := c.cc.Invoke(ctx, "/provider.Provider/Match", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) Lookup(ctx context.Context, in *dnc.LookupRequest, opts ...grpc.CallOption) (*dnc.LookupResponse, error) {
	out := new(dnc.LookupResponse)
	err := c.cc.Invoke(ctx, "/provider.Provider/Lookup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) Weight(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WeightResponse, error) {
	out := new(WeightResponse)
	err := c.cc.Invoke(ctx, "/provider.Provider/Weight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) GetConfiguration(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Configuration, error) {
	out := new(Configuration)
	err := c.cc.Invoke(ctx, "/provider.Provider/GetConfiguration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProviderServer is the server API for Provider service.
type ProviderServer interface {
	Name(context.Context, *Empty) (*NameResponse, error)
	Version(context.Context, *Empty) (*VersionResponse, error)
	Match(context.Context, *MatchRequest) (*MatchResponse, error)
	Lookup(context.Context, *dnc.LookupRequest) (*dnc.LookupResponse, error)
	Weight(context.Context, *Empty) (*WeightResponse, error)
	GetConfiguration(context.Context, *Empty) (*Configuration, error)
}

// UnimplementedProviderServer can be embedded to have forward compatible implementations.
type UnimplementedProviderServer struct {
}

func (*UnimplementedProviderServer) Name(ctx context.Context, req *Empty) (*NameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Name not implemented")
}
func (*UnimplementedProviderServer) Version(ctx context.Context, req *Empty) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (*UnimplementedProviderServer) Match(ctx context.Context, req *MatchRequest) (*MatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Match not implemented")
}
func (*UnimplementedProviderServer) Lookup(ctx context.Context, req *dnc.LookupRequest) (*dnc.LookupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lookup not implemented")
}
func (*UnimplementedProviderServer) Weight(ctx context.Context, req *Empty) (*WeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Weight not implemented")
}
func (*UnimplementedProviderServer) GetConfiguration(ctx context.Context, req *Empty) (*Configuration, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfiguration not implemented")
}

func RegisterProviderServer(s *grpc.Server, srv ProviderServer) {
	s.RegisterService(&_Provider_serviceDesc, srv)
}

func _Provider_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/provider.Provider/Name",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Name(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/provider.Provider/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Version(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_Match_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Match(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/provider.Provider/Match",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Match(ctx, req.(*MatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dnc.LookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/provider.Provider/Lookup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Lookup(ctx, req.(*dnc.LookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_Weight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Weight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/provider.Provider/Weight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Weight(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_GetConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).GetConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/provider.Provider/GetConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).GetConfiguration(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Provider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "provider.Provider",
	HandlerType: (*ProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Name",
			Handler:    _Provider_Name_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _Provider_Version_Handler,
		},
		{
			MethodName: "Match",
			Handler:    _Provider_Match_Handler,
		},
		{
			MethodName: "Lookup",
			Handler:    _Provider_Lookup_Handler,
		},
		{
			MethodName: "Weight",
			Handler:    _Provider_Weight_Handler,
		},
		{
			MethodName: "GetConfiguration",
			Handler:    _Provider_GetConfiguration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "git.liero.se/opentelco/go-swpx/proto/provider/provider.proto",
}
