// Code generated by protoc-gen-go. DO NOT EDIT.
// source: git.liero.se/opentelco/go-swpx/proto/dnc/dnc.proto

package dnc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Payload struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0b0dbf5e02461a8, []int{0}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Payload) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LookupResponse struct {
	OriginId             string   `protobuf:"bytes,1,opt,name=origin_id,json=originId,proto3" json:"origin_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookupResponse) Reset()         { *m = LookupResponse{} }
func (m *LookupResponse) String() string { return proto.CompactTextString(m) }
func (*LookupResponse) ProtoMessage()    {}
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0b0dbf5e02461a8, []int{1}
}

func (m *LookupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupResponse.Unmarshal(m, b)
}
func (m *LookupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupResponse.Marshal(b, m, deterministic)
}
func (m *LookupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupResponse.Merge(m, src)
}
func (m *LookupResponse) XXX_Size() int {
	return xxx_messageInfo_LookupResponse.Size(m)
}
func (m *LookupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LookupResponse proto.InternalMessageInfo

func (m *LookupResponse) GetOriginId() string {
	if m != nil {
		return m.OriginId
	}
	return ""
}

type LookupRequest struct {
	OriginId             string   `protobuf:"bytes,1,opt,name=origin_id,json=originId,proto3" json:"origin_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookupRequest) Reset()         { *m = LookupRequest{} }
func (m *LookupRequest) String() string { return proto.CompactTextString(m) }
func (*LookupRequest) ProtoMessage()    {}
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0b0dbf5e02461a8, []int{2}
}

func (m *LookupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupRequest.Unmarshal(m, b)
}
func (m *LookupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupRequest.Marshal(b, m, deterministic)
}
func (m *LookupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupRequest.Merge(m, src)
}
func (m *LookupRequest) XXX_Size() int {
	return xxx_messageInfo_LookupRequest.Size(m)
}
func (m *LookupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LookupRequest proto.InternalMessageInfo

func (m *LookupRequest) GetOriginId() string {
	if m != nil {
		return m.OriginId
	}
	return ""
}

func init() {
	proto.RegisterType((*Payload)(nil), "dnc.Payload")
	proto.RegisterType((*LookupResponse)(nil), "dnc.LookupResponse")
	proto.RegisterType((*LookupRequest)(nil), "dnc.LookupRequest")
}

func init() {
	proto.RegisterFile("git.liero.se/opentelco/go-swpx/proto/dnc/dnc.proto", fileDescriptor_f0b0dbf5e02461a8)
}

var fileDescriptor_f0b0dbf5e02461a8 = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4a, 0xcf, 0x2c, 0xd1,
	0xcb, 0xc9, 0x4c, 0x2d, 0xca, 0xd7, 0x2b, 0x4e, 0xd5, 0xcf, 0x2f, 0x48, 0xcd, 0x2b, 0x49, 0xcd,
	0x49, 0xce, 0xd7, 0x4f, 0xcf, 0xd7, 0x2d, 0x2e, 0x2f, 0xa8, 0xd0, 0x2f, 0x28, 0xca, 0x2f, 0xc9,
	0xd7, 0x4f, 0xc9, 0x4b, 0x06, 0x61, 0x3d, 0x30, 0x4f, 0x88, 0x39, 0x25, 0x2f, 0x59, 0xc9, 0x91,
	0x8b, 0x3d, 0x20, 0xb1, 0x32, 0x27, 0x3f, 0x31, 0x45, 0x48, 0x8a, 0x8b, 0x23, 0x23, 0xbf, 0xb8,
	0x24, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xce, 0x07, 0xc9, 0x15,
	0x24, 0x16, 0x17, 0x97, 0xe7, 0x17, 0xa5, 0x48, 0x30, 0x41, 0xe4, 0x60, 0x7c, 0x25, 0x5d, 0x2e,
	0x3e, 0x9f, 0xfc, 0xfc, 0xec, 0xd2, 0x82, 0xa0, 0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21,
	0x69, 0x2e, 0xce, 0xfc, 0xa2, 0xcc, 0xf4, 0xcc, 0xbc, 0xf8, 0xcc, 0x14, 0x98, 0x51, 0x10, 0x01,
	0xcf, 0x14, 0x25, 0x1d, 0x2e, 0x5e, 0x98, 0xf2, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0xbc, 0xaa, 0x9d,
	0xb4, 0xa2, 0x34, 0x88, 0xf5, 0x5a, 0x12, 0x1b, 0x98, 0x69, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0xb3, 0x23, 0x2e, 0xd1, 0x0d, 0x01, 0x00, 0x00,
}
