package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"git.liero.se/opentelco/go-swpx/fleet/graph/mappers"
	"git.liero.se/opentelco/go-swpx/fleet/graph/model"
	"git.liero.se/opentelco/go-swpx/proto/go/fleet/devicepb"
)

// Device is the resolver for the device field.
func (r *configurationResolver) Device(ctx context.Context, obj *model.Configuration) (*model.Device, error) {
	if obj == nil {
		return nil, fmt.Errorf("configuration is nil, cannot get device for nil configuration")
	}

	if obj.Device == nil {
		return nil, fmt.Errorf("device is nil, cannot get device for nil configuration")
	}

	if obj.Device.ID == "" {
		return &model.Device{}, nil
	}

	device, err := r.devices.GetByID(ctx, &devicepb.GetByIDParameters{Id: obj.Device.ID})
	if err != nil {
		return nil, err
	}
	return mappers.ToDevice(device).ToGQL(), nil
}

// Configuration returns ConfigurationResolver implementation.
func (r *Resolver) Configuration() ConfigurationResolver { return &configurationResolver{r} }

type configurationResolver struct{ *Resolver }
