package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"

	"git.liero.se/opentelco/go-swpx/fleet/graph/mappers"
	"git.liero.se/opentelco/go-swpx/fleet/graph/model"
	"git.liero.se/opentelco/go-swpx/fleet/internal"
	"git.liero.se/opentelco/go-swpx/proto/go/fleet/devicepb"
)

// Events is the resolver for the events field.
func (r *deviceResolver) Events(ctx context.Context, obj *model.Device, limit *int, offset *int) (*model.EventConnection, error) {
	res, err := r.devices.ListEvents(ctx, &devicepb.ListEventsParameters{
		DeviceId: obj.ID,
		Limit:    internal.PointerIntToPointerInt64(limit),
		Offset:   internal.PointerIntToPointerInt64(offset),
	})
	if err != nil {
		return nil, err
	}
	result := &model.EventConnection{
		Events:   mappers.DeviceEvents(res.Events).ToGQL(),
		PageInfo: mappers.PageInfo{res.PageInfo}.ToGQL(),
	}
	return result, nil
}

// Changes is the resolver for the changes field.
func (r *deviceResolver) Changes(ctx context.Context, obj *model.Device, limit *int, offset *int) (*model.ChangeConnection, error) {
	res, err := r.devices.ListChanges(ctx, &devicepb.ListChangesParameters{
		DeviceId: obj.ID,
		Limit:    internal.PointerIntToPointerInt64(limit),
		Offset:   internal.PointerIntToPointerInt64(offset),
	})
	if err != nil {
		return nil, err
	}
	result := &model.ChangeConnection{
		Changes:  mappers.DeviceChanges(res.Changes).ToGQL(),
		PageInfo: mappers.PageInfo{res.PageInfo}.ToGQL(),
	}
	return result, nil
}

// Device returns DeviceResolver implementation.
func (r *Resolver) Device() DeviceResolver { return &deviceResolver{r} }

type deviceResolver struct{ *Resolver }
