package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"

	"git.liero.se/opentelco/go-swpx/fleet/graph/mappers"
	"git.liero.se/opentelco/go-swpx/fleet/graph/model"
)

// Devices is the resolver for the devices field.
func (r *queryResolver) Devices(ctx context.Context, params *model.ListDevicesParams) (*model.ListDeviceResponse, error) {
	res, err := r.devices.List(ctx, params.ToProto())
	if err != nil {
		return nil, err
	}

	return mappers.ToDeviceListResponse(res).ToGQL(), nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
